### ISSUE TITLE
Startup error due to prometheus

### ISSUE THREAD

**Issue by mrjohnson22** [tulir/mautrix-facebook#100]
After the latest updates, my bridge hits a fatal error at startup due to something in prometheus:

```
[2020-09-18 02:00:34,587] [CRITICAL@mau.init] Unexpected error in main event loop                                                                                                                                  
Traceback (most recent call last):
  File "<PATH>/mautrix-facebook/lib/python3.7/site-packages/mautrix/util/program.py", line 190, in _run
    self.loop.run_until_complete(self.start())
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "<PATH>/mautrix-facebook/lib/python3.7/site-packages/mautrix_facebook/__main__.py", line 81, in start
    await super().start()
  File "<PATH>/mautrix-facebook/lib/python3.7/site-packages/mautrix/bridge/bridge.py", line 150, in start
    await super().start()
  File "<PATH>/mautrix-facebook/lib/python3.7/site-packages/mautrix/util/program.py", line 213, in start
    await asyncio.gather(*(self.startup_actions or []))
  File "<PATH>/mautrix-facebook/lib/python3.7/site-packages/mautrix_facebook/user.py", line 247, in load_session
    METRIC_LOGGED_IN.labels('fbid', self.fbid).state('true')
  File "<PATH>/mautrix-facebook/lib/python3.7/site-packages/prometheus_client/metrics.py", line 147, in labels
    raise ValueError('No label names were set when constructing %s' % self)
ValueError: No label names were set when constructing stateset:bridge_logged_in
```

This error occurs even though I have `metrics.enabled` set to `false`.

Reverting back to d3a8cc8 avoids this error and allows the bridge to start successfully.

**Comment by erdnaxeli** [comment]
For those using the docker image, the latest working tag is `d3a8cc8802346ee4a21567f10d528e512cd89e65-amd64`.

**Comment by mrjohnson22** [comment]
Confirmed fixed, thanks!
