### ISSUE TITLE
profile photos not displaying 

### ISSUE THREAD

**Issue by MeGilles** [tulir/mautrix-facebook#107]
Hello,
Profile photos not displaying on my server. 
When I enter the `sync --contacts` command, bot replies "Syncing complete" but in the logs i have 
```
Fetched 42 contacts
```
or sometimes
```
Nov 03 17:28:43 eve python[3342]: [2020-11-03 17:28:43,779] [DEBUG@mau.user.@user:example.com] Fetching contacts...
Nov 03 17:28:44 eve python[3342]: [2020-11-03 17:28:44,040] [ERROR@mau.user.@user:example.com] Failed to sync contacts
Nov 03 17:28:44 eve python[3342]: Traceback (most recent call last):
Nov 03 17:28:44 eve python[3342]:   File "/srv/matrix-bridges/mautrix-facebook/lib/python3.7/site-packages/mautrix_facebook/user.py", line 402, in sync_contacts
Nov 03 17:28:44 eve python[3342]:     users = await self.client.fetch_users()
Nov 03 17:28:44 eve python[3342]:   File "/srv/matrix-bridges/mautrix-facebook/lib/python3.7/site-packages/fbchat/_client.py", line 49, in fetch_users
Nov 03 17:28:44 eve python[3342]:     j = await self.session._payload_post("/chat/user_info_all", data)
Nov 03 17:28:44 eve python[3342]:   File "/srv/matrix-bridges/mautrix-facebook/lib/python3.7/site-packages/fbchat/_session.py", line 633, in _payload_post
Nov 03 17:28:44 eve python[3342]:     _exception.handle_payload_error(j)
Nov 03 17:28:44 eve python[3342]:   File "/srv/matrix-bridges/mautrix-facebook/lib/python3.7/site-packages/fbchat/_exception.py", line 139, in handle_payload_error
Nov 03 17:28:44 eve python[3342]:     raise error_cls(j["errorSummary"], description=j["errorDescription"], code=code)
Nov 03 17:28:44 eve python[3342]: fbchat.ExternalError: #1390008 Vous ne pouvez pas utiliser cette fonctionnalité pour le moment: {'__html': '<ul class="uiList _4kg _6-h _6-j _6-i"><li>Nous limitons le nombre de fois que vous pouvez publier, commenter ou faire autre chose dans un laps de temps donné afin de protéger la communauté contre le spam. Vous pouvez réessayer plus tard. <a href="https://www.facebook.com/help/177066345680802"> En savoir plus</a></li><li>Si vous pensez que ceci ne va pas à l’encontre des Standards de la communauté, <a href="">dites-le nous</a>.</li></ul>'}
Nov 03 17:28:44 eve python[3342]: [2020-11-03 17:28:44,581] [INFO@aiohttp.access] ::1 [03/Nov/2020:16:28:44 +0000] "PUT /transactions/2219?access_token=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx HTTP/1.1" 200 158 "-" "Synapse/1.22.1"
```
The error message roughly translate to : "You cannot use this functionality for the moment. We limit the number of times you can publish, comment ore make something else in a defined lapse of time to protect the community against spam. You can try again later. <link> Learn more. </link>  If you thinks it does not go against community standards <link>tell us</link>."

## More info 
I have the default `update_avatar_initial_sync: true` in my config.yaml file

Is it due to a bad configuration of my synapse server or do others experience the same issue?

**Comment by mrjohnson22** [comment]
Many photos/avatars don't display for me either, even after `sync --contacts`, but no "failed to sync contacts" error appears in my logs.

It seems like the only people whose avatars aren't loaded are people who aren't in my Facebook friends list. But in the past, avatars for non-friends did load properly.
