### ISSUE TITLE
Animated stickers does not get bridged

### ISSUE THREAD

**Issue by hooger** [tulir/mautrix-facebook#116]
Hello guys,

for some time animated stickers are not received. I got the log slice that corresponds to the event, I pasted it below. I hope I didn't cut anything that is crucial (and hope, I removed everything that shouldn't be published :D ).

```
[2020-12-30 21:41:55,310] [DEBUG@paho.mqtt.client] Sending PINGREQ
[2020-12-30 21:41:55,513] [DEBUG@mau.user.@gergely:horvath.club] Setting foreground status to True
[2020-12-30 21:41:55,515] [DEBUG@paho.mqtt.client] Sending PUBLISH (d0, q1, r0, m239), 'b'/foreground_state'', ... (19 bytes)
[2020-12-30 21:41:55,517] [DEBUG@paho.mqtt.client] Received PINGRESP
[2020-12-30 21:41:55,702] [DEBUG@paho.mqtt.client] Received PUBACK (Mid: 239)
[2020-12-30 21:41:56,984] [DEBUG@paho.mqtt.client] Received PUBLISH (d0, q1, r1, m15741), '/t_ms', ...  (2357 bytes)
[2020-12-30 21:41:56,985] [DEBUG@paho.mqtt.client] Sending PUBACK (Mid: 15741)
[2020-12-30 21:41:56,986] [DEBUG@fbchat] MQTT payload: /t_ms, {'deltas': [{'attachments': [{'mercury': {'sticker_attachment': {'id': 'STICKER_ATTACHMENT_ID', 'pack': {'id': 'ID'}, 'label': 'kiss', 'frame_count': 12, 'frame_rate': 125, 'frames_per_row': 4, 'frames_per_column': 3, 'sprite_image_2x': {'uri': 'URL'}, 'sprite_image': {'uri': 'URL'}, 'padded_sprite_image': {'uri': 'URL'}, 'padded_sprite_image_2x': {'uri': 'URL'}, 'url': 'URL', 'height': 240, 'width': 240}}}], 'data': {}, 'irisSeqId': 'IRISSEQID', 'irisTags': ['strict_user_privacy_enforcement', 'iris_post_process'], 'messageMetadata': {'actorFbId': 'ID', 'cid': {'canonicalParticipantFbids': ['ID', 'ID']}, 'folderId': {'systemFolderId': 'INBOX'}, 'messageId': 'mid.ID', 'offlineThreadingId': 'ID', 'tags': ['source:chat:light_speed', 'app_id:APPID'], 'threadKey': {'otherUserFbId': 'FBID'}, 'threadReadStateEffect': 'MARK_UNREAD', 'timestamp': '1609364516731', 'unsendType': 'deny_for_non_sender', 'skipBumpThread': False}, 'requestContext': {'apiArgs': {}}, 'stickerId': 'STICKER_ATTACHMENT_ID', 'class': 'NewMessage'}], 'firstDeltaSeqId': IRISSEQID, 'lastIssuedSeqId': IRISSEQID, 'queueEntityId': ID}
[2020-12-30 21:41:57,147] [DEBUG@paho.mqtt.client] Received PUBLISH (d0, q0, r1, m0), '/t_ms', ...  (381 bytes)
[2020-12-30 21:41:57,147] [DEBUG@fbchat] MQTT payload: /t_ms, {'deltas': [{'actionTimestampMs': '1609364516759', 'actorFbId': 'ID', 'irisSeqId': 'ID', 'irisTags': ['strict_user_privacy_enforcement', 'iris_post_process'], 'requestContext': {'apiArgs': {}}, 'threadKey': {'otherUserFbId': 'ID'}, 'watermarkTimestampMs': '1609364516646', 'class': 'ReadReceipt'}], 'firstDeltaSeqId': ID, 'lastIssuedSeqId': ID, 'queueEntityId': ID}
[2020-12-30 21:41:57,315] [DEBUG@mau.user.@gergely:horvath.club] Handling facebook event of type <class 'fbchat.MessageEvent'>
[2020-12-30 21:41:57,319] [DEBUG@mau.user.@gergely:horvath.club] Handling facebook event of type <class 'fbchat.ThreadsRead'>
[2020-12-30 21:41:58,039] [DEBUG@PIL.PngImagePlugin] STREAM b'IHDR' 16 13
[2020-12-30 21:41:58,041] [DEBUG@PIL.PngImagePlugin] STREAM b'bKGD' 41 6
[2020-12-30 21:41:58,043] [DEBUG@PIL.PngImagePlugin] b'bKGD' 41 6 (unknown)
[2020-12-30 21:41:58,045] [DEBUG@PIL.PngImagePlugin] STREAM b'IDAT' 59 32768
[2020-12-30 21:42:04,976] [ERROR@mau.portal.ID<->ID] Error handling Facebook message mid.$mid
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/mautrix_facebook/portal.py", line 697, in handle_facebook_message
    await self._handle_facebook_message(source, sender, message)
  File "/usr/lib/python3.8/site-packages/mautrix_facebook/portal.py", line 727, in _handle_facebook_message
    event_ids = [await self._handle_facebook_sticker(
  File "/usr/lib/python3.8/site-packages/mautrix_facebook/portal.py", line 799, in _handle_facebook_sticker
    return await self._send_message(intent, event_type=EventType.STICKER,
  File "/usr/lib/python3.8/site-packages/mautrix_facebook/portal.py", line 774, in _send_message
    return await intent.send_message_event(self.mxid, event_type, content, **kwargs)
  File "/usr/lib/python3.8/site-packages/mautrix/appservice/api/intent.py", line 91, in wrapper
    return await __method(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/mautrix/appservice/api/intent.py", line 271, in send_message_event
    return await super().send_message_event(room_id, event_type, content, **kwargs)
  File "/usr/lib/python3.8/site-packages/mautrix/client/api/events.py", line 315, in send_message_event
    resp = await self.api.request(Method.PUT, url, content, **kwargs)
  File "/usr/lib/python3.8/site-packages/mautrix/api.py", line 233, in request
    return await self._send(method, full_url, content, query_params, headers or {})
  File "/usr/lib/python3.8/site-packages/mautrix/api.py", line 158, in _send
    raise make_request_error(http_status=response.status,
mautrix.errors.request.MBadJSON: Bad JSON value: float
[2020-12-30 21:42:05,281] [DEBUG@paho.mqtt.client] Received PUBLISH (d0, q0, r1, m0), '/orca_presence', ...  (96 bytes)
[2020-12-30 21:42:05,282] [DEBUG@fbchat] MQTT payload: /orca_presence, {'list_type': 'inc', 'list': [{'u': integer, 'p': 2, 'l': int, 'vc': 10, 'c': int}]}
[2020-12-30 21:42:05,333] [DEBUG@mau.user.@gergely:horvath.club] Handling facebook event of type <class 'fbchat.Presence'>

```

**Comment by tulir** [comment]
These probably work now
