### ISSUE TITLE
sqlite errors when running "alembic upgrade head" in python 3.6.9

### ISSUE THREAD

**Issue by 2ba29s** [tulir/mautrix-facebook#118]
I was following the instructions at https://github.com/tulir/mautrix-facebook/wiki/Bridge-setup
At the step of `$ alembic upgrade head` I got a stack trace:

```
(mautrix-facebook) super@paz:~/builds/mautrix-facebook$ alembic upgrade head
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade  -> c36b294b1f5f, Initial revision
INFO  [alembic.runtime.migration] Running upgrade c36b294b1f5f -> 3c5af010538a, Add fb_receiver to Message
INFO  [alembic.runtime.migration] Running upgrade 3c5af010538a -> 26341fb32054, Add custom puppet support
INFO  [alembic.runtime.migration] Running upgrade 26341fb32054 -> 1a1ea46dc3e1, Add reaction table
INFO  [alembic.runtime.migration] Running upgrade 1a1ea46dc3e1 -> 8e0f1142c8d5, Store custom puppet next_batch in database
INFO  [alembic.runtime.migration] Running upgrade 8e0f1142c8d5 -> 3355b59b191c, Add user <-> portal/puppet mappings to db
INFO  [alembic.runtime.migration] Running upgrade 3355b59b191c -> 44a02762423d, Store user agent in db
INFO  [alembic.runtime.migration] Running upgrade 44a02762423d -> c56c9a30b228, Add end-to-bridge encryption fields
INFO  [alembic.runtime.migration] Running upgrade c56c9a30b228 -> 97e9f7a3c070, Remove user agent from db
INFO  [alembic.runtime.migration] Running upgrade 97e9f7a3c070 -> a26da6af5cff, Add bridge notice room column for users
INFO  [alembic.runtime.migration] Running upgrade a26da6af5cff -> 76cb89f6b352, Add date and chat ID for messages
INFO  [alembic.runtime.migration] Running upgrade 76cb89f6b352 -> 54aecbd6187c, Store Matrix avatar URL in database
INFO  [alembic.runtime.migration] Running upgrade 54aecbd6187c -> 244273a86d81, Re-add user agent to db
INFO  [alembic.runtime.migration] Running upgrade 244273a86d81 -> 905a91536747, Switch to mautrix-python crypto
INFO  [alembic.runtime.migration] Running upgrade 905a91536747 -> 2162f7ae5365, Store encryption state event in db
INFO  [alembic.runtime.migration] Running upgrade 2162f7ae5365 -> 3c59aa2a3af9, Add messenger domain to db
INFO  [alembic.runtime.migration] Running upgrade 3c59aa2a3af9 -> 3d4f3a252006, Add double puppet base URL to puppet table
INFO  [alembic.runtime.migration] Running upgrade 3d4f3a252006 -> 4face019555a, Stop using size-limited string fields
INFO  [alembic.runtime.migration] Running upgrade 4face019555a -> f91274813e8c, Add profile set booleans to puppet table
Traceback (most recent call last):
  File "/home/super/builds/mautrix-facebook/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "/home/super/builds/mautrix-facebook/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 609, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: default value of column [matrix_registered] is not constant

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/super/builds/mautrix-facebook/bin/alembic", line 8, in <module>
    sys.exit(main())
  File "/home/super/builds/mautrix-facebook/lib/python3.6/site-packages/alembic/config.py", line 581, in main
    CommandLine(prog=prog).main(argv=argv)
  File "/home/super/builds/mautrix-facebook/lib/python3.6/site-packages/alembic/config.py", line 575, in main
    self.run_cmd(cfg, options)
  File "/home/super/builds/mautrix-facebook/lib/python3.6/site-packages/alembic/config.py", line 555, in run_cmd
    **dict((k, getattr(options, k, None)) for k in kwarg)
  File "/home/super/builds/mautrix-facebook/lib/python3.6/site-packages/alembic/command.py", line 298, in upgrade
    script.run_env()
  File "/home/super/builds/mautrix-facebook/lib/python3.6/site-packages/alembic/script/base.py", line 489, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/home/super/builds/mautrix-facebook/lib/python3.6/site-packages/alembic/util/pyfiles.py", line 98, in load_python_file
    module = load_module_py(module_id, path)
  File "/home/super/builds/mautrix-facebook/lib/python3.6/site-packages/alembic/util/compat.py", line 184, in load_module_py
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "alembic/env.py", line 53, in <module>
    run_migrations_online()
  File "alembic/env.py", line 47, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/home/super/builds/mautrix-facebook/lib/python3.6/site-packages/alembic/runtime/environment.py", line 846, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/home/super/builds/mautrix-facebook/lib/python3.6/site-packages/alembic/runtime/migration.py", line 522, in run_migrations
    step.migration_fn(**kw)
  File "/home/super/builds/mautrix-facebook/alembic/versions/f91274813e8c_add_profile_set_booleans_to_puppet_table.py", line 21, in upgrade
    batch_op.add_column(sa.Column('name_set', sa.Boolean(), server_default=sa.false(), nullable=False))
  File "/usr/lib/python3.6/contextlib.py", line 88, in __exit__
    next(self.gen)
  File "/home/super/builds/mautrix-facebook/lib/python3.6/site-packages/alembic/operations/base.py", line 353, in batch_alter_table
    impl.flush()
  File "/home/super/builds/mautrix-facebook/lib/python3.6/site-packages/alembic/operations/batch.py", line 116, in flush
    batch_impl._create(self.impl)
  File "/home/super/builds/mautrix-facebook/lib/python3.6/site-packages/alembic/operations/batch.py", line 358, in _create
    op_impl.create_table(self.new_table)
  File "/home/super/builds/mautrix-facebook/lib/python3.6/site-packages/alembic/ddl/impl.py", line 259, in create_table
    self._exec(schema.CreateTable(table))
  File "/home/super/builds/mautrix-facebook/lib/python3.6/site-packages/alembic/ddl/impl.py", line 141, in _exec
    return conn.execute(construct, *multiparams, **params)
  File "/home/super/builds/mautrix-facebook/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/home/super/builds/mautrix-facebook/lib/python3.6/site-packages/sqlalchemy/sql/ddl.py", line 72, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "/home/super/builds/mautrix-facebook/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1073, in _execute_ddl
    compiled,
  File "/home/super/builds/mautrix-facebook/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1317, in _execute_context
    e, statement, parameters, cursor, context
  File "/home/super/builds/mautrix-facebook/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1511, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/super/builds/mautrix-facebook/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/super/builds/mautrix-facebook/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "/home/super/builds/mautrix-facebook/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 609, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) default value of column [matrix_registered] is not constant
[SQL: 
CREATE TABLE _alembic_tmp_puppet (
        fbid VARCHAR NOT NULL, 
        name VARCHAR, 
        photo_id VARCHAR, 
        matrix_registered BOOLEAN DEFAULT (false) NOT NULL, 
        access_token TEXT, 
        custom_mxid VARCHAR(255), 
        next_batch VARCHAR(255), 
        base_url TEXT, 
        avatar_set BOOLEAN DEFAULT (0) NOT NULL, 
        name_set BOOLEAN DEFAULT (0) NOT NULL, 
        PRIMARY KEY (fbid), 
        CHECK (matrix_registered IN (0, 1)), 
        CHECK (avatar_set IN (0, 1)), 
        CHECK (name_set IN (0, 1)), 
        CHECK (name_set IN (0, 1))
)

]
(Background on this error at: http://sqlalche.me/e/13/e3q8)
```

I tracked the problem down to `alembic/versions/c36b294b1f5f_initial_revision.py`
```python
    sa.Column('matrix_registered', sa.Boolean(), server_default=sa.text('false'), nullable=False),
```

SQLite doesn't have a boolean type, and does not seem to appreciate using `sa.text('false')` here for a false value. We can use `sa.false()` from sqlalchemy instead, which should be more cross platform.

After I fixed this, I ran into another issue:

```
(mautrix-facebook) super@paz:~/builds/mautrix-facebook$ alembic upgrade head
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade  -> c36b294b1f5f, Initial revision
INFO  [alembic.runtime.migration] Running upgrade c36b294b1f5f -> 3c5af010538a, Add fb_receiver to Message
INFO  [alembic.runtime.migration] Running upgrade 3c5af010538a -> 26341fb32054, Add custom puppet support
INFO  [alembic.runtime.migration] Running upgrade 26341fb32054 -> 1a1ea46dc3e1, Add reaction table
INFO  [alembic.runtime.migration] Running upgrade 1a1ea46dc3e1 -> 8e0f1142c8d5, Store custom puppet next_batch in database
INFO  [alembic.runtime.migration] Running upgrade 8e0f1142c8d5 -> 3355b59b191c, Add user <-> portal/puppet mappings to db
INFO  [alembic.runtime.migration] Running upgrade 3355b59b191c -> 44a02762423d, Store user agent in db
INFO  [alembic.runtime.migration] Running upgrade 44a02762423d -> c56c9a30b228, Add end-to-bridge encryption fields
INFO  [alembic.runtime.migration] Running upgrade c56c9a30b228 -> 97e9f7a3c070, Remove user agent from db
INFO  [alembic.runtime.migration] Running upgrade 97e9f7a3c070 -> a26da6af5cff, Add bridge notice room column for users
INFO  [alembic.runtime.migration] Running upgrade a26da6af5cff -> 76cb89f6b352, Add date and chat ID for messages
INFO  [alembic.runtime.migration] Running upgrade 76cb89f6b352 -> 54aecbd6187c, Store Matrix avatar URL in database
INFO  [alembic.runtime.migration] Running upgrade 54aecbd6187c -> 244273a86d81, Re-add user agent to db
INFO  [alembic.runtime.migration] Running upgrade 244273a86d81 -> 905a91536747, Switch to mautrix-python crypto
INFO  [alembic.runtime.migration] Running upgrade 905a91536747 -> 2162f7ae5365, Store encryption state event in db
INFO  [alembic.runtime.migration] Running upgrade 2162f7ae5365 -> 3c59aa2a3af9, Add messenger domain to db
INFO  [alembic.runtime.migration] Running upgrade 3c59aa2a3af9 -> 3d4f3a252006, Add double puppet base URL to puppet table
INFO  [alembic.runtime.migration] Running upgrade 3d4f3a252006 -> 4face019555a, Stop using size-limited string fields
INFO  [alembic.runtime.migration] Running upgrade 4face019555a -> f91274813e8c, Add profile set booleans to puppet table
Traceback (most recent call last):
  File "/home/super/builds/mautrix-facebook/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "/home/super/builds/mautrix-facebook/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 609, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such column: true

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/super/builds/mautrix-facebook/bin/alembic", line 8, in <module>
    sys.exit(main())
  File "/home/super/builds/mautrix-facebook/lib/python3.6/site-packages/alembic/config.py", line 581, in main
    CommandLine(prog=prog).main(argv=argv)
  File "/home/super/builds/mautrix-facebook/lib/python3.6/site-packages/alembic/config.py", line 575, in main
    self.run_cmd(cfg, options)
  File "/home/super/builds/mautrix-facebook/lib/python3.6/site-packages/alembic/config.py", line 555, in run_cmd
    **dict((k, getattr(options, k, None)) for k in kwarg)
  File "/home/super/builds/mautrix-facebook/lib/python3.6/site-packages/alembic/command.py", line 298, in upgrade
    script.run_env()
  File "/home/super/builds/mautrix-facebook/lib/python3.6/site-packages/alembic/script/base.py", line 489, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/home/super/builds/mautrix-facebook/lib/python3.6/site-packages/alembic/util/pyfiles.py", line 98, in load_python_file
    module = load_module_py(module_id, path)
  File "/home/super/builds/mautrix-facebook/lib/python3.6/site-packages/alembic/util/compat.py", line 184, in load_module_py
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "alembic/env.py", line 53, in <module>
    run_migrations_online()
  File "alembic/env.py", line 47, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/home/super/builds/mautrix-facebook/lib/python3.6/site-packages/alembic/runtime/environment.py", line 846, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/home/super/builds/mautrix-facebook/lib/python3.6/site-packages/alembic/runtime/migration.py", line 522, in run_migrations
    step.migration_fn(**kw)
  File "/home/super/builds/mautrix-facebook/alembic/versions/f91274813e8c_add_profile_set_booleans_to_puppet_table.py", line 24, in upgrade
    op.execute("UPDATE puppet SET name_set=true WHERE name<>''")
  File "<string>", line 8, in execute
  File "<string>", line 3, in execute
  File "/home/super/builds/mautrix-facebook/lib/python3.6/site-packages/alembic/operations/ops.py", line 2260, in execute
    return operations.invoke(op)
  File "/home/super/builds/mautrix-facebook/lib/python3.6/site-packages/alembic/operations/base.py", line 373, in invoke
    return fn(self, operation)
  File "/home/super/builds/mautrix-facebook/lib/python3.6/site-packages/alembic/operations/toimpl.py", line 178, in execute_sql
    operation.sqltext, execution_options=operation.execution_options
  File "/home/super/builds/mautrix-facebook/lib/python3.6/site-packages/alembic/ddl/impl.py", line 144, in execute
    self._exec(sql, execution_options)
  File "/home/super/builds/mautrix-facebook/lib/python3.6/site-packages/alembic/ddl/impl.py", line 141, in _exec
    return conn.execute(construct, *multiparams, **params)
  File "/home/super/builds/mautrix-facebook/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/home/super/builds/mautrix-facebook/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/super/builds/mautrix-facebook/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1130, in _execute_clauseelement
    distilled_params,
  File "/home/super/builds/mautrix-facebook/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1317, in _execute_context
    e, statement, parameters, cursor, context
  File "/home/super/builds/mautrix-facebook/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1511, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/super/builds/mautrix-facebook/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/super/builds/mautrix-facebook/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "/home/super/builds/mautrix-facebook/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 609, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: true
[SQL: UPDATE puppet SET name_set=true WHERE name<>'']
(Background on this error at: http://sqlalche.me/e/13/e3q8)
```

Again this is a problem with booleans - in alembic/versions/c36b294b1f5f_initial_revision.py:

```python
    op.execute("UPDATE puppet SET name_set=true WHERE name<>''")
    op.execute("UPDATE puppet SET avatar_set=true WHERE photo_id<>''")
```

Again we can use sqlalchemy instead rather than having our query as a string:

```python
    puppet = sa.table("puppet")
    puppet.update().where(len(puppet.name) > 0).values(name_set=sa.true(), avatar_set=sa.true())
```

I ran into this issue on
Ubuntu 18.04
which is running
sqlite3 3.22.0-1ubuntu0.4
python3 3.6.9

I did not encounter this issue on
Manjaro
which is running
sqlite3 3.34.0-1
python 3.9.1

I figure this problem comes from something to do with python 3.6? I know that the instructions say that 3.7 is required, but fixing this is not hard and would support Ubuntu 18.04 (which I figured would be a common deployment target).

PR Incoming...

**Comment by tulir** [comment]
SQLite does have boolean literals, but Ubuntu 18.04 is too old for that

**Comment by 2ba29s** [comment]
Yup. Would it be ok if you either merge my PR or add the requirement for SQLite version to the wiki? Looks like it's SQLite 3.23 (https://www.sqlite.org/releaselog/3_23_0.html).

**Comment by tulir** [comment]
I'm probably going to drop SQLite support instead
