### ISSUE TITLE
UnicodeDecodeError when receiving an image

### ISSUE THREAD

**Issue by tohojo** [tulir/mautrix-facebook#127]
Getting this traceback on the master branch when receiving an image (a GIF in this instance):

```
Jan 28 08:01:07 matrix python[470268]: [2021-01-28 08:01:07,530] [ERROR@mau.user.@xxxx:xx.xx.mqtt] Error in incoming MQTT message handler
Jan 28 08:01:07 matrix python[470268]: Traceback (most recent call last):
Jan 28 08:01:07 matrix python[470268]:   File "/opt/venvs/mautrix-facebook/lib/python3.7/site-packages/maufbapi/mqtt/conn.py", line 298, in _on_message_handler
Jan 28 08:01:07 matrix python[470268]:     self._on_message_sync(message.payload)
Jan 28 08:01:07 matrix python[470268]:   File "/opt/venvs/mautrix-facebook/lib/python3.7/site-packages/maufbapi/mqtt/conn.py", line 282, in _on_message_sync
Jan 28 08:01:07 matrix python[470268]:     parsed = MessageSyncPayload.from_thrift(payload)
Jan 28 08:01:07 matrix python[470268]:   File "/opt/venvs/mautrix-facebook/lib/python3.7/site-packages/maufbapi/thrift/autospec.py", line 43, in from_thrift
Jan 28 08:01:07 matrix python[470268]:     return ThriftReader(data).read_struct(cls)
Jan 28 08:01:07 matrix python[470268]:   File "/opt/venvs/mautrix-facebook/lib/python3.7/site-packages/maufbapi/thrift/read.py", line 275, in read_struct
Jan 28 08:01:07 matrix python[470268]:     args[field_meta.name] = self.read_val_recursive(field_meta.rtype)
Jan 28 08:01:07 matrix python[470268]:   File "/opt/venvs/mautrix-facebook/lib/python3.7/site-packages/maufbapi/thrift/read.py", line 239, in read_val_recursive
Jan 28 08:01:07 matrix python[470268]:     return set(data) if rtype.type == TType.SET else list(data)
Jan 28 08:01:07 matrix python[470268]:   File "/opt/venvs/mautrix-facebook/lib/python3.7/site-packages/maufbapi/thrift/read.py", line 238, in <genexpr>
Jan 28 08:01:07 matrix python[470268]:     data = (self.read_val_recursive(rtype.item_type) for _ in range(length))
Jan 28 08:01:07 matrix python[470268]:   File "/opt/venvs/mautrix-facebook/lib/python3.7/site-packages/maufbapi/thrift/read.py", line 216, in read_val_recursive
Jan 28 08:01:07 matrix python[470268]:     val = self.read_struct(rtype.python_type)
Jan 28 08:01:07 matrix python[470268]:   File "/opt/venvs/mautrix-facebook/lib/python3.7/site-packages/maufbapi/thrift/read.py", line 275, in read_struct
Jan 28 08:01:07 matrix python[470268]:     args[field_meta.name] = self.read_val_recursive(field_meta.rtype)
Jan 28 08:01:07 matrix python[470268]:   File "/opt/venvs/mautrix-facebook/lib/python3.7/site-packages/maufbapi/thrift/read.py", line 216, in read_val_recursive
Jan 28 08:01:07 matrix python[470268]:     val = self.read_struct(rtype.python_type)
Jan 28 08:01:07 matrix python[470268]:   File "/opt/venvs/mautrix-facebook/lib/python3.7/site-packages/maufbapi/thrift/read.py", line 275, in read_struct
Jan 28 08:01:07 matrix python[470268]:     args[field_meta.name] = self.read_val_recursive(field_meta.rtype)
Jan 28 08:01:07 matrix python[470268]:   File "/opt/venvs/mautrix-facebook/lib/python3.7/site-packages/maufbapi/thrift/read.py", line 239, in read_val_recursive
Jan 28 08:01:07 matrix python[470268]:     return set(data) if rtype.type == TType.SET else list(data)
Jan 28 08:01:07 matrix python[470268]:   File "/opt/venvs/mautrix-facebook/lib/python3.7/site-packages/maufbapi/thrift/read.py", line 238, in <genexpr>
Jan 28 08:01:07 matrix python[470268]:     data = (self.read_val_recursive(rtype.item_type) for _ in range(length))
Jan 28 08:01:07 matrix python[470268]:   File "/opt/venvs/mautrix-facebook/lib/python3.7/site-packages/maufbapi/thrift/read.py", line 216, in read_val_recursive
Jan 28 08:01:07 matrix python[470268]:     val = self.read_struct(rtype.python_type)
Jan 28 08:01:07 matrix python[470268]:   File "/opt/venvs/mautrix-facebook/lib/python3.7/site-packages/maufbapi/thrift/read.py", line 275, in read_struct
Jan 28 08:01:07 matrix python[470268]:     args[field_meta.name] = self.read_val_recursive(field_meta.rtype)
Jan 28 08:01:07 matrix python[470268]:   File "/opt/venvs/mautrix-facebook/lib/python3.7/site-packages/maufbapi/thrift/read.py", line 216, in read_val_recursive
Jan 28 08:01:07 matrix python[470268]:     val = self.read_struct(rtype.python_type)
Jan 28 08:01:07 matrix python[470268]:   File "/opt/venvs/mautrix-facebook/lib/python3.7/site-packages/maufbapi/thrift/read.py", line 275, in read_struct
Jan 28 08:01:07 matrix python[470268]:     args[field_meta.name] = self.read_val_recursive(field_meta.rtype)
Jan 28 08:01:07 matrix python[470268]:   File "/opt/venvs/mautrix-facebook/lib/python3.7/site-packages/maufbapi/thrift/read.py", line 231, in read_val_recursive
Jan 28 08:01:07 matrix python[470268]:     for _ in range(length)
Jan 28 08:01:07 matrix python[470268]:   File "/opt/venvs/mautrix-facebook/lib/python3.7/site-packages/maufbapi/thrift/read.py", line 231, in <dictcomp>
Jan 28 08:01:07 matrix python[470268]:     for _ in range(length)
Jan 28 08:01:07 matrix python[470268]:   File "/opt/venvs/mautrix-facebook/lib/python3.7/site-packages/maufbapi/thrift/read.py", line 244, in read_val_recursive
Jan 28 08:01:07 matrix python[470268]:     return rtype.python_type(self.read_val(rtype.type).decode("utf-8"))
Jan 28 08:01:07 matrix python[470268]: UnicodeDecodeError: 'utf-8' codec can't decode byte 0xef in position 24: invalid continuation byte
```

**Comment by caesar** [comment]
I'm getting the same error when receiving any image (and the image fails to come through to Matrix).

I also get the same error when sending an image, but the image is successfully sent anyway.

I thought it might be because my database encoding wasn't utf8, but I've recreated the database with utf8 encoding and out didn't make any difference.

**Comment by tohojo** [comment]
From the backtrace, it's this bit that's being hit:

https://github.com/tulir/mautrix-facebook/blob/77c0dc43ec227ebbe4da0783b328ae3679561ed0/maufbapi/thrift/read.py#L241-L244

Which to me just looks like it's trying to decode something that's not a string as UTF-8. Maybe it's just the raw image data as a binary?

Interestingly, when the periodic 'refresh' runs, that is able to successfully backfill the image...

**Comment by tulir** [comment]
Added logging to show what it failed to decode

**Comment by caesar** [comment]
@tulir I am on latest master and am not getting any additional info logged beyond what @tohojo posted above.

Here is my log output from attempting to send myself a small PNG:

```log
Jan 30 17:20:23 canopus python[20258]: [2021-01-30 17:20:23,440] [DEBUG@mau.mx] Received Matrix event $sDwrRhTtwH3cYuxe3glWD4_rvKynzw2iHbKfVIpaY7M from @caesar:schinas.net in !JUYNWWhXxIUUBWiphJ:schinas.net
Jan 30 17:20:24 canopus python[20258]: [2021-01-30 17:20:24,638] [ERROR@mau.user.@caesar:schinas.net.mqtt] Error in incoming MQTT message handler
Jan 30 17:20:24 canopus python[20258]: Traceback (most recent call last):
Jan 30 17:20:24 canopus python[20258]:   File "/srv/matrix/bridges/facebook/mautrix-facebook/lib/python3.7/site-packages/maufbapi/mqtt/conn.py", line 298, in _on_message_handler
Jan 30 17:20:24 canopus python[20258]:     self._on_message_sync(message.payload)
Jan 30 17:20:24 canopus python[20258]:   File "/srv/matrix/bridges/facebook/mautrix-facebook/lib/python3.7/site-packages/maufbapi/mqtt/conn.py", line 282, in _on_message_sync
Jan 30 17:20:24 canopus python[20258]:     parsed = MessageSyncPayload.from_thrift(payload)
Jan 30 17:20:24 canopus python[20258]:   File "/srv/matrix/bridges/facebook/mautrix-facebook/lib/python3.7/site-packages/maufbapi/thrift/autospec.py", line 43, in from_thrift
Jan 30 17:20:24 canopus python[20258]:     return ThriftReader(data).read_struct(cls)
Jan 30 17:20:24 canopus python[20258]:   File "/srv/matrix/bridges/facebook/mautrix-facebook/lib/python3.7/site-packages/maufbapi/thrift/read.py", line 275, in read_struct
Jan 30 17:20:24 canopus python[20258]:     args[field_meta.name] = self.read_val_recursive(field_meta.rtype)
Jan 30 17:20:24 canopus python[20258]:   File "/srv/matrix/bridges/facebook/mautrix-facebook/lib/python3.7/site-packages/maufbapi/thrift/read.py", line 239, in read_val_recursive
Jan 30 17:20:24 canopus python[20258]:     return set(data) if rtype.type == TType.SET else list(data)
Jan 30 17:20:24 canopus python[20258]:   File "/srv/matrix/bridges/facebook/mautrix-facebook/lib/python3.7/site-packages/maufbapi/thrift/read.py", line 238, in <genexpr>
Jan 30 17:20:24 canopus python[20258]:     data = (self.read_val_recursive(rtype.item_type) for _ in range(length))
Jan 30 17:20:24 canopus python[20258]:   File "/srv/matrix/bridges/facebook/mautrix-facebook/lib/python3.7/site-packages/maufbapi/thrift/read.py", line 216, in read_val_recursive
Jan 30 17:20:24 canopus python[20258]:     val = self.read_struct(rtype.python_type)
Jan 30 17:20:24 canopus python[20258]:   File "/srv/matrix/bridges/facebook/mautrix-facebook/lib/python3.7/site-packages/maufbapi/thrift/read.py", line 275, in read_struct
Jan 30 17:20:24 canopus python[20258]:     args[field_meta.name] = self.read_val_recursive(field_meta.rtype)
Jan 30 17:20:24 canopus python[20258]:   File "/srv/matrix/bridges/facebook/mautrix-facebook/lib/python3.7/site-packages/maufbapi/thrift/read.py", line 216, in read_val_recursive
Jan 30 17:20:24 canopus python[20258]:     val = self.read_struct(rtype.python_type)
Jan 30 17:20:24 canopus python[20258]:   File "/srv/matrix/bridges/facebook/mautrix-facebook/lib/python3.7/site-packages/maufbapi/thrift/read.py", line 275, in read_struct
Jan 30 17:20:24 canopus python[20258]:     args[field_meta.name] = self.read_val_recursive(field_meta.rtype)
Jan 30 17:20:24 canopus python[20258]:   File "/srv/matrix/bridges/facebook/mautrix-facebook/lib/python3.7/site-packages/maufbapi/thrift/read.py", line 239, in read_val_recursive
Jan 30 17:20:24 canopus python[20258]:     return set(data) if rtype.type == TType.SET else list(data)
Jan 30 17:20:24 canopus python[20258]:   File "/srv/matrix/bridges/facebook/mautrix-facebook/lib/python3.7/site-packages/maufbapi/thrift/read.py", line 238, in <genexpr>
Jan 30 17:20:24 canopus python[20258]:     data = (self.read_val_recursive(rtype.item_type) for _ in range(length))
Jan 30 17:20:24 canopus python[20258]:   File "/srv/matrix/bridges/facebook/mautrix-facebook/lib/python3.7/site-packages/maufbapi/thrift/read.py", line 216, in read_val_recursive
Jan 30 17:20:24 canopus python[20258]:     val = self.read_struct(rtype.python_type)
Jan 30 17:20:24 canopus python[20258]:   File "/srv/matrix/bridges/facebook/mautrix-facebook/lib/python3.7/site-packages/maufbapi/thrift/read.py", line 275, in read_struct
Jan 30 17:20:24 canopus python[20258]:     args[field_meta.name] = self.read_val_recursive(field_meta.rtype)
Jan 30 17:20:24 canopus python[20258]:   File "/srv/matrix/bridges/facebook/mautrix-facebook/lib/python3.7/site-packages/maufbapi/thrift/read.py", line 216, in read_val_recursive
Jan 30 17:20:24 canopus python[20258]:     val = self.read_struct(rtype.python_type)
Jan 30 17:20:24 canopus python[20258]:   File "/srv/matrix/bridges/facebook/mautrix-facebook/lib/python3.7/site-packages/maufbapi/thrift/read.py", line 275, in read_struct
Jan 30 17:20:24 canopus python[20258]:     args[field_meta.name] = self.read_val_recursive(field_meta.rtype)
Jan 30 17:20:24 canopus python[20258]:   File "/srv/matrix/bridges/facebook/mautrix-facebook/lib/python3.7/site-packages/maufbapi/thrift/read.py", line 231, in read_val_recursive
Jan 30 17:20:24 canopus python[20258]:     for _ in range(length)
Jan 30 17:20:24 canopus python[20258]:   File "/srv/matrix/bridges/facebook/mautrix-facebook/lib/python3.7/site-packages/maufbapi/thrift/read.py", line 231, in <dictcomp>
Jan 30 17:20:24 canopus python[20258]:     for _ in range(length)
Jan 30 17:20:24 canopus python[20258]:   File "/srv/matrix/bridges/facebook/mautrix-facebook/lib/python3.7/site-packages/maufbapi/thrift/read.py", line 244, in read_val_recursive
Jan 30 17:20:24 canopus python[20258]:     return rtype.python_type(self.read_val(rtype.type).decode("utf-8"))
Jan 30 17:20:24 canopus python[20258]: UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 4: invalid start byte
Jan 30 17:20:24 canopus python[20258]: [2021-01-30 17:20:24,962] [DEBUG@mau.portal.1472803448<->1472803448] Handled Matrix message $sDwrRhTtwH3cYuxe3glWD4_rvKynzw2iHbKfVIpaY7M -> mid.$cAAAAAFfJMnh9hZSpGV3VE9doeNjl / 6761332231458314469

```

**Comment by tulir** [comment]
That's not latest master

**Comment by caesar** [comment]
> That's not latest master

I ran `pip install --upgrade 'https://github.com/tulir/mautrix-facebook/tarball/master#egg=mautrix-facebook[all]` and restarted mautrix-facebook and Synapse.

What else should I do?

**Comment by caesar** [comment]
Okay, so per your comment in #130, I have now turned on `TRACE` level logging.

I now get the following additional output (for a JPG):

```log
Jan 30 17:52:28 canopus python[19688]: [2021-01-30 17:52:28,784] [TRACE@mau.user.@caesar:schinas.net.mqtt] Errored MQTT payload: b'\x19\x1c,\x1c\x1c\x16\xf0\xc9\xc9\xfc\n\x00\x18"mid.$cAAAAAFfJMnh9hbIGH13VGy6XHyUc\x16\xb8\x94\xf9\xf1\xd2\xcb\x8d\xd5\xbb\x01\x16\xf0\xc9\xc9\xfc\n\x16\xbe\xf8\xe5\xc6\xea]\x11)(\x10source:chat:orca\x16app_id:256002347743983\x15\x06\x12(\ncan_unsend\\*\x16\xf0\xc9\xc9\xfc\n\x00\x00I\x1c\x18\x0f241726030862753\x18\nimage/jpeg\x182144178727_241726034196086_639476852948218920_n.jpg\x16\xc2\xe6\x9e\xa3\xa7\xf6m\x16\xe6\xca\x06\\\x15\xc0\x07\x15\x80\x05\x1b\x05X\x00\x93\x02https://scontent.xx.fbcdn.net/v/t1.15752-9/fr/cp0/e15/q65/144178727_241726034196086_639476852948218920_n.jpg?_nc_cat=109&ccb=2&_nc_sid=58c789&_nc_ohc=qM0sTiq7-_cAX-YOiNp&_nc_ad=z-m&_nc_cid=0&_nc_ht=scontent.xx&tp=14&_nc_rmd=260&oh=a0f43263aa078ad7003d3fc30687b4f9&oe=603CD03B\x02\x93\x02https://scontent.xx.fbcdn.net/v/t1.15752-9/fr/cp0/e15/q65/144178727_241726034196086_639476852948218920_n.jpg?_nc_cat=109&ccb=2&_nc_sid=58c789&_nc_ohc=qM0sTiq7-_cAX-YOiNp&_nc_ad=z-m&_nc_cid=0&_nc_ht=scontent.xx&tp=14&_nc_rmd=260&oh=a0f43263aa078ad7003d3fc30687b4f9&oe=603CD03B\x04\x93\x02https://scontent.xx.fbcdn.net/v/t1.15752-9/fr/cp0/e15/q65/144178727_241726034196086_639476852948218920_n.jpg?_nc_cat=109&ccb=2&_nc_sid=58c789&_nc_ohc=qM0sTiq7-_cAX-YOiNp&_nc_ad=z-m&_nc_cid=0&_nc_ht=scontent.xx&tp=14&_nc_rmd=260&oh=a0f43263aa078ad7003d3fc30687b4f9&oe=603CD03B\x06\x98\x02https://scontent.xx.fbcdn.net/v/t1.15752-0/cp0/e15/q65/p240x240/144178727_241726034196086_639476852948218920_n.jpg?_nc_cat=109&ccb=2&_nc_sid=58c789&_nc_ohc=qM0sTiq7-_cAX-YOiNp&_nc_ad=z-m&_nc_cid=0&_nc_ht=scontent.xx&tp=3&_nc_rmd=260&oh=5f1f6c78bad89dcaa4ab627eec17f0f6&oe=6039B336\x08\x98\x02https://scontent.xx.fbcdn.net/v/t1.15752-0/cp0/e15/q65/p240x240/144178727_241726034196086_639476852948218920_n.jpg?_nc_cat=109&ccb=2&_nc_sid=58c789&_nc_ohc=qM0sTiq7-_cAX-YOiNp&_nc_ad=z-m&_nc_cid=0&_nc_ht=scontent.xx&tp=3&_nc_rmd=260&oh=5f1f6c78bad89dcaa4ab627eec17f0f6&oe=6039B336\x15\x02H\x03jpg"\x00;\x01\x88\x0cis_thumbnail\x011\x01\xde\x0f\x00+\x00\x00\x00\x16\xcc\xee\x12\x16\xcc\xee\x12\x16\xf0\xc9\xc9\xfc\n\x00'
```

**Comment by tulir** [comment]
I think someone somewhere found out that the tarball install doesn't actually upgrade and you need `'git+https://github.com/tulir/mautrix-facebook.git#egg=mautrix-facebook[all]'` instead.

That payload is enough, but parsing it seems to work fine for me, so the bug might have already been fixed.

**Comment by caesar** [comment]
Hmm, strange. Okay so I re-ran the upgrade with `'git+https://github.com/tulir/mautrix-facebook.git#egg=mautrix-facebook[all]'`, and then restarted mautrix-facebook, but still the same error.

Interestingly as @tohojo noted, when restarting mautrix-facebook, it does backfill the image if it was the last post in the thread.

Here is the full log output, after upgrading:

```log
Jan 30 18:00:33 canopus python[19892]: [2021-01-30 18:00:33,944] [DEBUG@paho.mqtt.client] Received PUBLISH (d0, q1, r0, m16111), '59', ...  (544 bytes)
Jan 30 18:00:33 canopus python[19892]: [2021-01-30 18:00:33,945] [DEBUG@paho.mqtt.client] Sending PUBACK (Mid: 16111)
Jan 30 18:00:33 canopus python[19892]: [2021-01-30 18:00:33,946] [ERROR@mau.user.@caesar:schinas.net.mqtt] Error in incoming MQTT message handler
Jan 30 18:00:33 canopus python[19892]: Traceback (most recent call last):
Jan 30 18:00:33 canopus python[19892]:   File "/srv/matrix/bridges/facebook/mautrix-facebook/lib/python3.7/site-packages/maufbapi/thrift/read.py", line 248, in read_val_recursive
Jan 30 18:00:33 canopus python[19892]:     return rtype.python_type(self.read_val(rtype.type).decode("utf-8"))
Jan 30 18:00:33 canopus python[19892]: UnicodeDecodeError: 'utf-8' codec can't decode byte 0x93 in position 55: invalid start byte
Jan 30 18:00:33 canopus python[19892]: During handling of the above exception, another exception occurred:
Jan 30 18:00:33 canopus python[19892]: Traceback (most recent call last):
Jan 30 18:00:33 canopus python[19892]:   File "/srv/matrix/bridges/facebook/mautrix-facebook/lib/python3.7/site-packages/maufbapi/mqtt/conn.py", line 305, in _on_message_handler
Jan 30 18:00:33 canopus python[19892]:     self._on_message_sync(message.payload)
Jan 30 18:00:33 canopus python[19892]:   File "/srv/matrix/bridges/facebook/mautrix-facebook/lib/python3.7/site-packages/maufbapi/mqtt/conn.py", line 284, in _on_message_sync
Jan 30 18:00:33 canopus python[19892]:     parsed = MessageSyncPayload.from_thrift(payload)
Jan 30 18:00:33 canopus python[19892]:   File "/srv/matrix/bridges/facebook/mautrix-facebook/lib/python3.7/site-packages/maufbapi/thrift/autospec.py", line 43, in from_thrift
Jan 30 18:00:33 canopus python[19892]:     return ThriftReader(data).read_struct(cls)
Jan 30 18:00:33 canopus python[19892]:   File "/srv/matrix/bridges/facebook/mautrix-facebook/lib/python3.7/site-packages/maufbapi/thrift/read.py", line 283, in read_struct
Jan 30 18:00:33 canopus python[19892]:     args[field_meta.name] = self.read_val_recursive(field_meta.rtype, field_path=fp)
Jan 30 18:00:33 canopus python[19892]:   File "/srv/matrix/bridges/facebook/mautrix-facebook/lib/python3.7/site-packages/maufbapi/thrift/read.py", line 242, in read_val_recursive
Jan 30 18:00:33 canopus python[19892]:     return set(data) if rtype.type == TType.SET else list(data)
Jan 30 18:00:33 canopus python[19892]:   File "/srv/matrix/bridges/facebook/mautrix-facebook/lib/python3.7/site-packages/maufbapi/thrift/read.py", line 241, in <genexpr>
Jan 30 18:00:33 canopus python[19892]:     for i in range(length))
Jan 30 18:00:33 canopus python[19892]:   File "/srv/matrix/bridges/facebook/mautrix-facebook/lib/python3.7/site-packages/maufbapi/thrift/read.py", line 217, in read_val_recursive
Jan 30 18:00:33 canopus python[19892]:     val = self.read_struct(rtype.python_type, field_path=field_path)
Jan 30 18:00:33 canopus python[19892]:   File "/srv/matrix/bridges/facebook/mautrix-facebook/lib/python3.7/site-packages/maufbapi/thrift/read.py", line 283, in read_struct
Jan 30 18:00:33 canopus python[19892]:     args[field_meta.name] = self.read_val_recursive(field_meta.rtype, field_path=fp)
Jan 30 18:00:33 canopus python[19892]:   File "/srv/matrix/bridges/facebook/mautrix-facebook/lib/python3.7/site-packages/maufbapi/thrift/read.py", line 217, in read_val_recursive
Jan 30 18:00:33 canopus python[19892]:     val = self.read_struct(rtype.python_type, field_path=field_path)
Jan 30 18:00:33 canopus python[19892]:   File "/srv/matrix/bridges/facebook/mautrix-facebook/lib/python3.7/site-packages/maufbapi/thrift/read.py", line 283, in read_struct
Jan 30 18:00:33 canopus python[19892]:     args[field_meta.name] = self.read_val_recursive(field_meta.rtype, field_path=fp)
Jan 30 18:00:33 canopus python[19892]:   File "/srv/matrix/bridges/facebook/mautrix-facebook/lib/python3.7/site-packages/maufbapi/thrift/read.py", line 242, in read_val_recursive
Jan 30 18:00:33 canopus python[19892]:     return set(data) if rtype.type == TType.SET else list(data)
Jan 30 18:00:33 canopus python[19892]:   File "/srv/matrix/bridges/facebook/mautrix-facebook/lib/python3.7/site-packages/maufbapi/thrift/read.py", line 241, in <genexpr>
Jan 30 18:00:33 canopus python[19892]:     for i in range(length))
Jan 30 18:00:33 canopus python[19892]:   File "/srv/matrix/bridges/facebook/mautrix-facebook/lib/python3.7/site-packages/maufbapi/thrift/read.py", line 217, in read_val_recursive
Jan 30 18:00:33 canopus python[19892]:     val = self.read_struct(rtype.python_type, field_path=field_path)
Jan 30 18:00:33 canopus python[19892]:   File "/srv/matrix/bridges/facebook/mautrix-facebook/lib/python3.7/site-packages/maufbapi/thrift/read.py", line 283, in read_struct
Jan 30 18:00:33 canopus python[19892]:     args[field_meta.name] = self.read_val_recursive(field_meta.rtype, field_path=fp)
Jan 30 18:00:33 canopus python[19892]:   File "/srv/matrix/bridges/facebook/mautrix-facebook/lib/python3.7/site-packages/maufbapi/thrift/read.py", line 217, in read_val_recursive
Jan 30 18:00:33 canopus python[19892]:     val = self.read_struct(rtype.python_type, field_path=field_path)
Jan 30 18:00:33 canopus python[19892]:   File "/srv/matrix/bridges/facebook/mautrix-facebook/lib/python3.7/site-packages/maufbapi/thrift/read.py", line 283, in read_struct
Jan 30 18:00:33 canopus python[19892]:     args[field_meta.name] = self.read_val_recursive(field_meta.rtype, field_path=fp)
Jan 30 18:00:33 canopus python[19892]:   File "/srv/matrix/bridges/facebook/mautrix-facebook/lib/python3.7/site-packages/maufbapi/thrift/read.py", line 233, in read_val_recursive
Jan 30 18:00:33 canopus python[19892]:     for i in range(length)
Jan 30 18:00:33 canopus python[19892]:   File "/srv/matrix/bridges/facebook/mautrix-facebook/lib/python3.7/site-packages/maufbapi/thrift/read.py", line 233, in <dictcomp>
Jan 30 18:00:33 canopus python[19892]:     for i in range(length)
Jan 30 18:00:33 canopus python[19892]:   File "/srv/matrix/bridges/facebook/mautrix-facebook/lib/python3.7/site-packages/maufbapi/thrift/read.py", line 250, in read_val_recursive
Jan 30 18:00:33 canopus python[19892]:     raise ValueError(f"Failed to decode string at {field_path}: {e}")
Jan 30 18:00:33 canopus python[19892]: ValueError: Failed to decode string at root.items[0].message.attachments[0].image_info.previews[3.val]: 'utf-8' codec can't decode byte 0x93 in position 55: invalid start byte
Jan 30 18:00:33 canopus python[19892]: [2021-01-30 18:00:33,947] [TRACE@mau.user.@caesar:schinas.net.mqtt] Errored MQTT payload: b'\x19\x1c,\x1c\x1c\x16\xf0\xc9\xc9\xfc\n\x00\x18"mid.$cAAAAAFfJMnh9hblsml3VHQhjrEZo\x16\xd0\x99\xe2\xba\x8c\xc2\x8e\xd5\xbb\x01\x16\xf0\xc9\xc9\xfc\n\x16\xb4\x92\xa1\xc7\xea]\x11)(\x10source:chat:orca\x16app_id:256002347743983\x15\x06\x12(\ncan_unsend\\*\x16\xf0\xc9\xc9\xfc\n\x00\x00I\x1c\x18\x0f755504112046953\x18\nimage/jpeg\x182144569262_755504115380286_394699094117200885_n.jpg\x16\xd2\xcd\xcc\xa3\x90\xc8\xd7\x02\x16\xf0\x8e\t\\\x15\xd0\x05\x15\xc0\x07\x1b\x05X\x00\x93\x02https://scontent.xx.fbcdn.net/v/t1.15752-9/fr/cp0/e15/q65/144569262_755504115380286_394699094117200885_n.jpg?_nc_cat=100&ccb=2&_nc_sid=58c789&_nc_ohc=0r0a39q8tzsAX_PXdKE&_nc_ad=z-m&_nc_cid=0&_nc_ht=scontent.xx&tp=14&_nc_rmd=260&oh=b6ca4765a9ba6aabbe9b1e516a43cb23&oe=60395CF4\x02\x93\x02https://scontent.xx.fbcdn.net/v/t1.15752-9/fr/cp0/e15/q65/144569262_755504115380286_394699094117200885_n.jpg?_nc_cat=100&ccb=2&_nc_sid=58c789&_nc_ohc=0r0a39q8tzsAX_PXdKE&_nc_ad=z-m&_nc_cid=0&_nc_ht=scontent.xx&tp=14&_nc_rmd=260&oh=b6ca4765a9ba6aabbe9b1e516a43cb23&oe=60395CF4\x04\x93\x02https://scontent.xx.fbcdn.net/v/t1.15752-9/fr/cp0/e15/q65/144569262_755504115380286_394699094117200885_n.jpg?_nc_cat=100&ccb=2&_nc_sid=58c789&_nc_ohc=0r0a39q8tzsAX_PXdKE&_nc_ad=z-m&_nc_cid=0&_nc_ht=scontent.xx&tp=14&_nc_rmd=260&oh=b6ca4765a9ba6aabbe9b1e516a43cb23&oe=60395CF4\x06\x98\x02https://scontent.xx.fbcdn.net/v/t1.15752-0/cp0/e15/q65/p280x280/144569262_755504115380286_394699094117200885_n.jpg?_nc_cat=100&ccb=2&_nc_sid=58c789&_nc_ohc=0r0a39q8tzsAX_PXdKE&_nc_ad=z-m&_nc_cid=0&_nc_ht=scontent.xx&tp=3&_nc_rmd=260&oh=8ec33bd8945711065944a5acbbef4a03&oe=603A0904\x08\x98\x02https://scontent.xx.fbcdn.net/v/t1.15752-0/cp0/e15/q65/p280x280/144569262_755504115380286_394699094117200885_n.jpg?_nc_cat=100&ccb=2&_nc_sid=58c789&_nc_ohc=0r0a39q8tzsAX_PXdKE&_nc_ad=z-m&_nc_cid=0&_nc_ht=scontent.xx&tp=3&_nc_rmd=260&oh=8ec33bd8945711065944a5acbbef4a03&oe=603A0904\x15\x02H\x03jpg"\x00;\x01\x88\x0cis_thumbnail\x011\x01\xde\x0f\x00+\x00\x00\x00\x16\xce\xee\x12\x16\xce\xee\x12\x16\xf0\xc9\xc9\xfc\n\x00'
```

**Comment by tulir** [comment]
huh, looks like it only happens with python 3.7

**Comment by caesar** [comment]
Ahh, interesting! I am indeed on Python 3.7.3 (on Debian 10).

FWIW I deleted my mautrix-facebook venv and did a clean install but it made no difference.

**Comment by caesar** [comment]
I can confirm that there is no error on Python 3.9.

*But*, the received image is *tiny* (480x320), though the image that was sent was high resolution.
Any ideas / is that a known (separate) issue?

**Comment by tulir** [comment]
Image resolution is fine for me, You can check the first link in `previews` or `alt_previews` in the "Facebook MQTT event content" trace log, that's the one the bridge prefers to download

**Comment by tohojo** [comment]
After updating to latest master I'm seeing what appears to be the same error as in https://github.com/tulir/mautrix-facebook/issues/127#issuecomment-770253241 (`ValueError: Failed to decode string at root.items[0].message.attachments[0].image_info.previews[3.val]: 'utf-8' codec can't decode byte 0xf0 in position 33: invalid continuation byte`) - also running on Python 3.7 on Debian Buster...

Do you need the payload as well, or is @caesar's example from above sufficient?
