### ISSUE TITLE
ValueError: 14 is not a valid TType

### ISSUE THREAD

**Issue by tohojo** [tulir/mautrix-facebook#130]
Got another error on receiving a message - think this was supposed to be an image:

```
Jan 30 15:05:41 matrix python[526871]: [2021-01-30 15:05:41,554] [ERROR@mau.user.@<redacted>.mqtt] Error in incoming MQTT message handler
Jan 30 15:05:41 matrix python[526871]: ValueError: 14 is not a valid TType
Jan 30 15:05:41 matrix python[526871]: During handling of the above exception, another exception occurred:
Jan 30 15:05:41 matrix python[526871]: Traceback (most recent call last):
Jan 30 15:05:41 matrix python[526871]:   File "/opt/venvs/mautrix-facebook/lib/python3.7/site-packages/maufbapi/mqtt/conn.py", line 298, in _on_message_handler
Jan 30 15:05:41 matrix python[526871]:     self._on_message_sync(message.payload)
Jan 30 15:05:41 matrix python[526871]:   File "/opt/venvs/mautrix-facebook/lib/python3.7/site-packages/maufbapi/mqtt/conn.py", line 282, in _on_message_sync
Jan 30 15:05:41 matrix python[526871]:     parsed = MessageSyncPayload.from_thrift(payload)
Jan 30 15:05:41 matrix python[526871]:   File "/opt/venvs/mautrix-facebook/lib/python3.7/site-packages/maufbapi/thrift/autospec.py", line 43, in from_thrift
Jan 30 15:05:41 matrix python[526871]:     return ThriftReader(data).read_struct(cls)
Jan 30 15:05:41 matrix python[526871]:   File "/opt/venvs/mautrix-facebook/lib/python3.7/site-packages/maufbapi/thrift/read.py", line 275, in read_struct
Jan 30 15:05:41 matrix python[526871]:     args[field_meta.name] = self.read_val_recursive(field_meta.rtype)
Jan 30 15:05:41 matrix python[526871]:   File "/opt/venvs/mautrix-facebook/lib/python3.7/site-packages/maufbapi/thrift/read.py", line 239, in read_val_recursive
Jan 30 15:05:41 matrix python[526871]:     return set(data) if rtype.type == TType.SET else list(data)
Jan 30 15:05:41 matrix python[526871]:   File "/opt/venvs/mautrix-facebook/lib/python3.7/site-packages/maufbapi/thrift/read.py", line 238, in <genexpr>
Jan 30 15:05:41 matrix python[526871]:     data = (self.read_val_recursive(rtype.item_type) for _ in range(length))
Jan 30 15:05:41 matrix python[526871]:   File "/opt/venvs/mautrix-facebook/lib/python3.7/site-packages/maufbapi/thrift/read.py", line 216, in read_val_recursive
Jan 30 15:05:41 matrix python[526871]:     val = self.read_struct(rtype.python_type)
Jan 30 15:05:41 matrix python[526871]:   File "/opt/venvs/mautrix-facebook/lib/python3.7/site-packages/maufbapi/thrift/read.py", line 275, in read_struct
Jan 30 15:05:41 matrix python[526871]:     args[field_meta.name] = self.read_val_recursive(field_meta.rtype)
Jan 30 15:05:41 matrix python[526871]:   File "/opt/venvs/mautrix-facebook/lib/python3.7/site-packages/maufbapi/thrift/read.py", line 216, in read_val_recursive
Jan 30 15:05:41 matrix python[526871]:     val = self.read_struct(rtype.python_type)
Jan 30 15:05:41 matrix python[526871]:   File "/opt/venvs/mautrix-facebook/lib/python3.7/site-packages/maufbapi/thrift/read.py", line 275, in read_struct
Jan 30 15:05:41 matrix python[526871]:     args[field_meta.name] = self.read_val_recursive(field_meta.rtype)
Jan 30 15:05:41 matrix python[526871]:   File "/opt/venvs/mautrix-facebook/lib/python3.7/site-packages/maufbapi/thrift/read.py", line 239, in read_val_recursive
Jan 30 15:05:41 matrix python[526871]:     return set(data) if rtype.type == TType.SET else list(data)
Jan 30 15:05:41 matrix python[526871]:   File "/opt/venvs/mautrix-facebook/lib/python3.7/site-packages/maufbapi/thrift/read.py", line 238, in <genexpr>
Jan 30 15:05:41 matrix python[526871]:     data = (self.read_val_recursive(rtype.item_type) for _ in range(length))
Jan 30 15:05:41 matrix python[526871]:   File "/opt/venvs/mautrix-facebook/lib/python3.7/site-packages/maufbapi/thrift/read.py", line 216, in read_val_recursive
Jan 30 15:05:41 matrix python[526871]:     val = self.read_struct(rtype.python_type)
Jan 30 15:05:41 matrix python[526871]:   File "/opt/venvs/mautrix-facebook/lib/python3.7/site-packages/maufbapi/thrift/read.py", line 259, in read_struct
Jan 30 15:05:41 matrix python[526871]:     field_type, field_index = self.read_field()
Jan 30 15:05:41 matrix python[526871]:   File "/opt/venvs/mautrix-facebook/lib/python3.7/site-packages/maufbapi/thrift/read.py", line 96, in read_field
Jan 30 15:05:41 matrix python[526871]:     type = TType(byte & 0x0f)
Jan 30 15:05:41 matrix python[526871]:   File "/opt/venvs/mautrix-facebook/lib/python3.7/enum.py", line 310, in __call__
Jan 30 15:05:41 matrix python[526871]:     return cls.__new__(cls, value)
Jan 30 15:05:41 matrix python[526871]:   File "/opt/venvs/mautrix-facebook/lib/python3.7/enum.py", line 564, in __new__
Jan 30 15:05:41 matrix python[526871]:     raise exc
Jan 30 15:05:41 matrix python[526871]:   File "/opt/venvs/mautrix-facebook/lib/python3.7/enum.py", line 548, in __new__
Jan 30 15:05:41 matrix python[526871]:     result = cls._missing_(value)
Jan 30 15:05:41 matrix python[526871]:   File "/opt/venvs/mautrix-facebook/lib/python3.7/enum.py", line 577, in _missing_
Jan 30 15:05:41 matrix python[526871]:     raise ValueError("%r is not a valid %s" % (value, cls.__name__))
```

**Comment by tulir** [comment]
Enable `trace` level logs and send the content ("Errored MQTT payload: ...")

**Comment by tohojo** [comment]
Not sure if this is the same type of message as before, and it shows up as a UnicodeDecodeError now, but I also think you changed the parsing code around some, right?

AFAICT what's missing on the matrix side was reactions to a previously-posted GIF attachment (the GIF image itself did get bridged). Here's the error:

```
Feb 01 05:47:26 matrix python[596630]: [2021-02-01 05:47:26,346] [ERROR@mau.user.@toke:toke.dk.mqtt] Error in incoming MQTT message handler
Feb 01 05:47:26 matrix python[596630]: Traceback (most recent call last):
Feb 01 05:47:26 matrix python[596630]:   File "/opt/venvs/mautrix-facebook/lib/python3.7/site-packages/maufbapi/mqtt/conn.py", line 298, in _on_message_handler
Feb 01 05:47:26 matrix python[596630]:     self._on_message_sync(message.payload)
Feb 01 05:47:26 matrix python[596630]:   File "/opt/venvs/mautrix-facebook/lib/python3.7/site-packages/maufbapi/mqtt/conn.py", line 287, in _on_message_sync
Feb 01 05:47:26 matrix python[596630]:     for event in item.get_parts():
Feb 01 05:47:26 matrix python[596630]:   File "/opt/venvs/mautrix-facebook/lib/python3.7/site-packages/maufbapi/types/mqtt/message.py", line 365, in get_parts
Feb 01 05:47:26 matrix python[596630]:     for inner_item in self.binary.parse().items:
Feb 01 05:47:26 matrix python[596630]:   File "/opt/venvs/mautrix-facebook/lib/python3.7/site-packages/maufbapi/types/mqtt/message.py", line 249, in parse
Feb 01 05:47:26 matrix python[596630]:     return MessageSyncInnerPayload.from_thrift(self.data)
Feb 01 05:47:26 matrix python[596630]:   File "/opt/venvs/mautrix-facebook/lib/python3.7/site-packages/maufbapi/thrift/autospec.py", line 43, in from_thrift
Feb 01 05:47:26 matrix python[596630]:     return ThriftReader(data).read_struct(cls)
Feb 01 05:47:26 matrix python[596630]:   File "/opt/venvs/mautrix-facebook/lib/python3.7/site-packages/maufbapi/thrift/read.py", line 275, in read_struct
Feb 01 05:47:26 matrix python[596630]:     args[field_meta.name] = self.read_val_recursive(field_meta.rtype)
Feb 01 05:47:26 matrix python[596630]:   File "/opt/venvs/mautrix-facebook/lib/python3.7/site-packages/maufbapi/thrift/read.py", line 239, in read_val_recursive
Feb 01 05:47:26 matrix python[596630]:     return set(data) if rtype.type == TType.SET else list(data)
Feb 01 05:47:26 matrix python[596630]:   File "/opt/venvs/mautrix-facebook/lib/python3.7/site-packages/maufbapi/thrift/read.py", line 238, in <genexpr>
Feb 01 05:47:26 matrix python[596630]:     data = (self.read_val_recursive(rtype.item_type) for _ in range(length))
Feb 01 05:47:26 matrix python[596630]:   File "/opt/venvs/mautrix-facebook/lib/python3.7/site-packages/maufbapi/thrift/read.py", line 216, in read_val_recursive
Feb 01 05:47:26 matrix python[596630]:     val = self.read_struct(rtype.python_type)
Feb 01 05:47:26 matrix python[596630]:   File "/opt/venvs/mautrix-facebook/lib/python3.7/site-packages/maufbapi/thrift/read.py", line 275, in read_struct
Feb 01 05:47:26 matrix python[596630]:     args[field_meta.name] = self.read_val_recursive(field_meta.rtype)
Feb 01 05:47:26 matrix python[596630]:   File "/opt/venvs/mautrix-facebook/lib/python3.7/site-packages/maufbapi/thrift/read.py", line 216, in read_val_recursive
Feb 01 05:47:26 matrix python[596630]:     val = self.read_struct(rtype.python_type)
Feb 01 05:47:26 matrix python[596630]:   File "/opt/venvs/mautrix-facebook/lib/python3.7/site-packages/maufbapi/thrift/read.py", line 275, in read_struct
Feb 01 05:47:26 matrix python[596630]:     args[field_meta.name] = self.read_val_recursive(field_meta.rtype)
Feb 01 05:47:26 matrix python[596630]:   File "/opt/venvs/mautrix-facebook/lib/python3.7/site-packages/maufbapi/thrift/read.py", line 216, in read_val_recursive
Feb 01 05:47:26 matrix python[596630]:     val = self.read_struct(rtype.python_type)
Feb 01 05:47:26 matrix python[596630]:   File "/opt/venvs/mautrix-facebook/lib/python3.7/site-packages/maufbapi/thrift/read.py", line 275, in read_struct
Feb 01 05:47:26 matrix python[596630]:     args[field_meta.name] = self.read_val_recursive(field_meta.rtype)
Feb 01 05:47:26 matrix python[596630]:   File "/opt/venvs/mautrix-facebook/lib/python3.7/site-packages/maufbapi/thrift/read.py", line 239, in read_val_recursive
Feb 01 05:47:26 matrix python[596630]:     return set(data) if rtype.type == TType.SET else list(data)
Feb 01 05:47:26 matrix python[596630]:   File "/opt/venvs/mautrix-facebook/lib/python3.7/site-packages/maufbapi/thrift/read.py", line 238, in <genexpr>
Feb 01 05:47:26 matrix python[596630]:     data = (self.read_val_recursive(rtype.item_type) for _ in range(length))
Feb 01 05:47:26 matrix python[596630]:   File "/opt/venvs/mautrix-facebook/lib/python3.7/site-packages/maufbapi/thrift/read.py", line 216, in read_val_recursive
Feb 01 05:47:26 matrix python[596630]:     val = self.read_struct(rtype.python_type)
Feb 01 05:47:26 matrix python[596630]:   File "/opt/venvs/mautrix-facebook/lib/python3.7/site-packages/maufbapi/thrift/read.py", line 275, in read_struct
Feb 01 05:47:26 matrix python[596630]:     args[field_meta.name] = self.read_val_recursive(field_meta.rtype)
Feb 01 05:47:26 matrix python[596630]:   File "/opt/venvs/mautrix-facebook/lib/python3.7/site-packages/maufbapi/thrift/read.py", line 216, in read_val_recursive
Feb 01 05:47:26 matrix python[596630]:     val = self.read_struct(rtype.python_type)
Feb 01 05:47:26 matrix python[596630]:   File "/opt/venvs/mautrix-facebook/lib/python3.7/site-packages/maufbapi/thrift/read.py", line 275, in read_struct
Feb 01 05:47:26 matrix python[596630]:     args[field_meta.name] = self.read_val_recursive(field_meta.rtype)
Feb 01 05:47:26 matrix python[596630]:   File "/opt/venvs/mautrix-facebook/lib/python3.7/site-packages/maufbapi/thrift/read.py", line 231, in read_val_recursive
Feb 01 05:47:26 matrix python[596630]:     for _ in range(length)
Feb 01 05:47:26 matrix python[596630]:   File "/opt/venvs/mautrix-facebook/lib/python3.7/site-packages/maufbapi/thrift/read.py", line 231, in <dictcomp>
Feb 01 05:47:26 matrix python[596630]:     for _ in range(length)
Feb 01 05:47:26 matrix python[596630]:   File "/opt/venvs/mautrix-facebook/lib/python3.7/site-packages/maufbapi/thrift/read.py", line 244, in read_val_recursive
Feb 01 05:47:26 matrix python[596630]:     return rtype.python_type(self.read_val(rtype.type).decode("utf-8"))
Feb 01 05:47:26 matrix python[596630]: UnicodeDecodeError: 'utf-8' codec can't decode byte 0xef in position 24: invalid continuation byte
Feb 01 05:47:26 matrix python[596630]: [2021-02-01 05:47:26,350] [TRACE@mau.user.@<redacted>.mqtt] Errored MQTT payload: b'\x19\x1c\x0cT\x18\xb6 \x19\x1c\x0cn\x1c\x1c\x1c&\xaa\x98\x9a\xf9\xcb\xe9\xd2\n\x00\x18"mid.$gAAqlpl-TRhV9i_SlHV3Wq9ckN3oL\x16\x96\xe8\xbb\xc3\xe4\xf5\xd5\xd6\xbb\x01\x16\xb4\xe6\xde\xf9\x03\x16\xba\xf4\xfa\xaa\xeb]9h\x05inbox\x04sent\x02tq\x1cblindly_apply_message_folder\x10source:chat:orca\x16app_id:256002347743983\x00\x18\x14Aske lever! \xf0\x9f\x98\x82\xf0\x9f\xa5\xb39\x0c\x0b\xe8\x0f\x01\x88\x07apiArgs\xf6\x01(7https://www.facebook.com/messaging/iris/postprocess.php&\xde\xeb\xfd\x8f\xa6\xb5t8\t294.0.0.0\x08\n$bcc48cb4-9b67-461c-9896-b4a40d4740579\x1b\x04\x88\x05layer\x03www\npush_phase\x02C3\tbuenopath4XIrisPostProcessorThriftController:postProcessDeltas\x07www_rev\n1003246267\x18\x11messenger_android\x12\x009\x08\x00\x1c\x1c\x1c&\xaa\x98\x9a\xf9\xcb\xe9\xd2\n\x00\x18"mid.$gAAqlpl-TRhV9jWbyYF3XCGQ7AQU0\x16\xe8\x94\x88\xb0\x87\x99\x84\xd7\xbb\x01\x16\xe2\xdb\xb0\x9d\x05\x16\xc0\xa9\x8d\xc2\xeb]9h\x10source:chat:orca\x16app_id:256002347743983\x02tq\ncg-enabled\x1cblindly_apply_message_folder\x05inbox\x15\x04\x12(\x13deny_for_non_sender\\\x16\xaa\x98\x9a\xf9\xcb\xe9\xd2\n\x00\x0c\xd4\x0f\x15\x00\x00\x00I\x1c\x18\x0f263087048680357\x18\timage/gif\x18250344010_629652870884324_8610379074415624192_n.gif\x16\xca\x8e\xa7\xa1\xd7\xd1w,\x16\x9e\xa6\x81\xdb\x82\xbd\xaa\x01(\x12Tenor GIF Keyboard\x18\x90\x02https://scontent.xx.fbcdn.net/v/t39.2081-6/c0.0.76.76a/p75x75/10734294_398580973627373_1478369539_n.png?_nc_cat=1&ccb=2&_nc_sid=eaa83b&_nc_ohc=jHp2E-a6bfkAX9ijuyK&_nc_ad=z-m&_nc_cid=0&_nc_ht=scontent.xx&_nc_tp=30&_nc_rmd=260&oh=a8f585a79a6c1bc03c2e1b574c0bda7e&oe=603F0983\x18\x14com.riffsy.FBMGIFApp\x16\xd0\xa2\xb4\xeb\x06\x1b\x00\x1c\x12\x12\x12\x12\x12\x006\x00\x00L\x15\xc8\x05\x15\x90\x03\x1b\x05X\x00\xef\x01https://cdn.fbsbx.com/v/t59.2708-21/50344010_629652870884324_8610379074415624192_n.gif?_nc_cat=103&fallback=1&ccb=2&_nc_sid=041f46&_nc_ohc=YCuPRNOkP0MAX87RYoL&_nc_ht=cdn.fbsbx.com&_nc_rmd=260&oh=c17f8bac997c86318a0b71e8dc08cd67&oe=60195624\x02\xef\x01https://cdn.fbsbx.com/v/t59.2708-21/50344010_629652870884324_8610379074415624192_n.gif?_nc_cat=103&fallback=1&ccb=2&_nc_sid=041f46&_nc_ohc=YCuPRNOkP0MAX87RYoL&_nc_ht=cdn.fbsbx.com&_nc_rmd=260&oh=c17f8bac997c86318a0b71e8dc08cd67&oe=60195624\x04\xef\x01https://cdn.fbsbx.com/v/t59.2708-21/50344010_629652870884324_8610379074415624192_n.gif?_nc_cat=103&fallback=1&ccb=2&_nc_sid=041f46&_nc_ohc=YCuPRNOkP0MAX87RYoL&_nc_ht=cdn.fbsbx.com&_nc_rmd=260&oh=c17f8bac997c86318a0b71e8dc08cd67&oe=60195624\x06\xef\x01https://cdn.fbsbx.com/v/t59.2708-21/50344010_629652870884324_8610379074415624192_n.gif?_nc_cat=103&fallback=1&ccb=2&_nc_sid=041f46&_nc_ohc=YCuPRNOkP0MAX87RYoL&_nc_ht=cdn.fbsbx.com&_nc_rmd=260&oh=c17f8bac997c86318a0b71e8dc08cd67&oe=60195624\x08\xef\x01https://cdn.fbsbx.com/v/t59.2708-21/50344010_629652870884324_8610379074415624192_n.gif?_nc_cat=103&fallback=1&ccb=2&_nc_sid=041f46&_nc_ohc=YCuPRNOkP0MAX87RYoL&_nc_ht=cdn.fbsbx.com&_nc_rmd=260&oh=c17f8bac997c86318a0b71e8dc08cd67&oe=60195624K\x05X\x00\xe5\x01https://cdn.fbsbx.com/v/t59.2708-21/100745814_632399550680961_840020750407565312_n.webp?_nc_cat=103&ccb=2&_nc_sid=041f46&_nc_ohc=hKoPp3ktXBkAX81Nen0&_nc_ht=cdn.fbsbx.com&_nc_rmd=260&oh=f214e2bc94ea766091f33f4f6ce0762d&oe=6019737F\x02\xe5\x01https://cdn.fbsbx.com/v/t59.2708-21/100745814_632399550680961_840020750407565312_n.webp?_nc_cat=103&ccb=2&_nc_sid=041f46&_nc_ohc=hKoPp3ktXBkAX81Nen0&_nc_ht=cdn.fbsbx.com&_nc_rmd=260&oh=f214e2bc94ea766091f33f4f6ce0762d&oe=6019737F\x04\xe5\x01https://cdn.fbsbx.com/v/t59.2708-21/100745814_632399550680961_840020750407565312_n.webp?_nc_cat=103&ccb=2&_nc_sid=041f46&_nc_ohc=hKoPp3ktXBkAX81Nen0&_nc_ht=cdn.fbsbx.com&_nc_rmd=260&oh=f214e2bc94ea766091f33f4f6ce0762d&oe=6019737F\x06\xe5\x01https://cdn.fbsbx.com/v/t59.2708-21/100745814_632399550680961_840020750407565312_n.webp?_nc_cat=103&ccb=2&_nc_sid=041f46&_nc_ohc=hKoPp3ktXBkAX81Nen0&_nc_ht=cdn.fbsbx.com&_nc_rmd=260&oh=f214e2bc94ea766091f33f4f6ce0762d&oe=6019737F\x08\xe5\x01https://cdn.fbsbx.com/v/t59.2708-21/100745814_632399550680961_840020750407565312_n.webp?_nc_cat=103&ccb=2&_nc_sid=041f46&_nc_ohc=hKoPp3ktXBkAX81Nen0&_nc_ht=cdn.fbsbx.com&_nc_rmd=260&oh=f214e2bc94ea766091f33f4f6ce0762d&oe=6019737F\x18\x03gif\x18\x04webp\x12\x00\x0b\xd2\x0f\x01\x88\x06fbtype\x045248\x18\x0f263087048680357%\x10\x1av\x8a\xb2\xb0\x8c\x05\x82\xf7\xbf\xc3\x04\xe2\xdb\xb0\x9d\x05\xd8\xa4\xb9\xde\x07\xa8\x8d\xda\xe5\x03\xa0\xd0\xf8\x89\n\xa8\xef\xd9\xc7\t!\x00+\x01\x88\x12attribution_app_id\x0f374882289330575\x06\xd0\x0f\xa4\xc1\x17\x06\xf2\x0f\x8e\x06\x0c\xd6\x0f\x1c\x18"mid.$gAAqlpl-TRhV9i_SlHV3Wq9ckN3oL\x00\x15\x00\x00\x9b\x01\x88\x07apiArgs\xa1\x02(8https://www.facebook.com/intern/agent/realtime_delivery/&\xde\xeb\xfd\x8f\xa6\xb5t8\x0e296.0.0.12.119\x08\n$53d7fe8e-5a79-4073-89f2-8cfc207816ad9\x1b\x04\x88\x05layer\x03www\npush_phase\x03C3e\tbuenopathXXRealtimeDeliveryThriftServerController:sendRealtimeDeliveryRequest:/t_sm:animated_image\x07www_rev\n1003246267\x18\x11messenger_android\x12\x00)\x86\xa8\x8d\xda\xe5\x03\x8a\xb2\xb0\x8c\x05\xd8\xa4\xb9\xde\x07\xb4\xe6\xde\xf9\x03\xa0\xd0\xf8\x89\n\xa8\xef\xd9\xc7\t\x82\xf7\xbf\xc3\x04\xe2\xdb\xb0\x9d\x05\x19H\x1fstrict_user_privacy_enforcement\x11iris_post_process-strict_user_privacy_enforcement_logging_block-strict_user_privacy_enforcement_feature_block\x00%\x00\x00\x00\x00\x00\x00\x16\xa4\xc1\x17\x16\xa4\xc1\x17\x16\xb4\xe6\xde\xf9\x03\x00'
```

**Comment by tohojo** [comment]
...and now I just realised I was also not running the latest master; used the git-based 'pip upgrade' and will keep an eye on whether I still get backtraces.
