### ISSUE TITLE
Failed to join room

### ISSUE THREAD

**Issue by waclaw66** [tulir/mautrix-facebook#132]
Getting this repeatedily...

```
úno 01 22:28:15 bolesiny.net python[1631053]: [2021-02-01 22:28:15,434] [INFO@mau.user.@waclaw:bolesiny.net] Loaded session successfully
úno 01 22:28:15 bolesiny.net python[1631053]: [2021-02-01 22:28:15,435] [INFO@mau.user.@waclaw:bolesiny.net] Running post-login actions
úno 01 22:28:15 bolesiny.net python[1631053]: [2021-02-01 22:28:15,435] [DEBUG@mau.user.@waclaw:bolesiny.net] Fetching threads...
úno 01 22:28:15 bolesiny.net python[1631053]: [2021-02-01 22:28:15,980] [DEBUG@mau.user.@waclaw:bolesiny.net] Syncing thread 591591745
úno 01 22:28:16 bolesiny.net python[1631053]: [2021-02-01 22:28:16,016] [DEBUG@mau.portal.591591745<->100006344554306] Not backfilling 591591745<->100006344554306: last activity is equal to most recent bridged message (1612208016609 >= 1612208016609)
úno 01 22:28:16 bolesiny.net python[1631053]: [2021-02-01 22:28:16,016] [DEBUG@mau.user.@waclaw:bolesiny.net] Syncing thread 100003939590628
úno 01 22:28:16 bolesiny.net python[1631053]: [2021-02-01 22:28:16,050] [DEBUG@mau.portal.100003939590628<->100006344554306] Backfilling history through @waclaw:bolesiny.net
úno 01 22:28:16 bolesiny.net python[1631053]: [2021-02-01 22:28:16,050] [DEBUG@mau.portal.100003939590628<->100006344554306] Fetching up to 1000 messages through 100006344554306
úno 01 22:28:16 bolesiny.net python[1631053]: [2021-02-01 22:28:16,721] [DEBUG@mau.portal.100003939590628<->100006344554306] Stopping fetching messages at mid.$cAAAAB3Hv1qZ8-ZVlN12yFAcLNUFU as message is older than newest bridged message (1609678462263 < 1609679670868)
úno 01 22:28:16 bolesiny.net python[1631053]: [2021-02-01 22:28:16,721] [DEBUG@mau.portal.100003939590628<->100006344554306] Got 1 messages from server
úno 01 22:28:16 bolesiny.net python[1631053]: [2021-02-01 22:28:16,723] [INFO@mau.portal.100003939590628<->100006344554306] Backfilled 1 messages through @waclaw:bolesiny.net
úno 01 22:28:16 bolesiny.net python[1631053]: [2021-02-01 22:28:16,723] [DEBUG@mau.user.@waclaw:bolesiny.net] Syncing thread 100000642065318
úno 01 22:28:16 bolesiny.net python[1631053]: [2021-02-01 22:28:16,757] [DEBUG@mau.portal.100000642065318<->100006344554306] Not backfilling 100000642065318<->100006344554306: no most recent message found
úno 01 22:28:16 bolesiny.net python[1631053]: [2021-02-01 22:28:16,764] [DEBUG@mau.user.@waclaw:bolesiny.net.mqtt] Connecting to Messenger MQTT
úno 01 22:28:16 bolesiny.net python[1631053]: [2021-02-01 22:28:16,894] [DEBUG@mau.user.@waclaw:bolesiny.net.mqtt] Re-creating sync queue after reconnect
úno 01 22:28:16 bolesiny.net python[1631053]: [2021-02-01 22:28:16,894] [DEBUG@mau.user.@waclaw:bolesiny.net] Sending bridge notice: Connected to Facebook Messenger
úno 01 22:28:16 bolesiny.net python[1631053]: [2021-02-01 22:28:16,904] [WARNING@mau.user.@waclaw:bolesiny.net] Failed to send bridge notice
úno 01 22:28:16 bolesiny.net python[1631053]: Traceback (most recent call last):
úno 01 22:28:16 bolesiny.net python[1631053]:   File "/opt/mautrix-facebook/lib/python3.9/site-packages/mautrix/appservice/api/intent.py", line 329, in ensure_joined
úno 01 22:28:16 bolesiny.net python[1631053]:     await self.join_room(room_id, max_retries=0)
úno 01 22:28:16 bolesiny.net python[1631053]:   File "/opt/mautrix-facebook/lib/python3.9/site-packages/mautrix/appservice/api/intent.py", line 83, in wrapper
úno 01 22:28:16 bolesiny.net python[1631053]:     return await __method(*args, **kwargs)
úno 01 22:28:16 bolesiny.net python[1631053]:   File "/opt/mautrix-facebook/lib/python3.9/site-packages/mautrix/client/api/rooms.py", line 252, in join_room
úno 01 22:28:16 bolesiny.net python[1631053]:     content = await self.api.request(Method.POST, Path.join[room_id_or_alias],
úno 01 22:28:16 bolesiny.net python[1631053]:   File "/opt/mautrix-facebook/lib/python3.9/site-packages/mautrix/api.py", line 233, in request
úno 01 22:28:16 bolesiny.net python[1631053]:     return await self._send(method, full_url, content, query_params, headers or {})
úno 01 22:28:16 bolesiny.net python[1631053]:   File "/opt/mautrix-facebook/lib/python3.9/site-packages/mautrix/api.py", line 158, in _send
úno 01 22:28:16 bolesiny.net python[1631053]:     raise make_request_error(http_status=response.status,
úno 01 22:28:16 bolesiny.net python[1631053]: mautrix.errors.request.MUnknown: No known servers
úno 01 22:28:16 bolesiny.net python[1631053]: The above exception was the direct cause of the following exception:
úno 01 22:28:16 bolesiny.net python[1631053]: Traceback (most recent call last):
úno 01 22:28:16 bolesiny.net python[1631053]:   File "/opt/mautrix-facebook/lib/python3.9/site-packages/mautrix_facebook/user.py", line 484, in send_bridge_notice
úno 01 22:28:16 bolesiny.net python[1631053]:     event_id = await self.az.intent.send_message(await self.get_notice_room(), content)
úno 01 22:28:16 bolesiny.net python[1631053]:   File "/opt/mautrix-facebook/lib/python3.9/site-packages/mautrix/appservice/api/intent.py", line 94, in wrapper
úno 01 22:28:16 bolesiny.net python[1631053]:     await __self.ensure_joined(room_id)
úno 01 22:28:16 bolesiny.net python[1631053]:   File "/opt/mautrix-facebook/lib/python3.9/site-packages/mautrix/appservice/api/intent.py", line 351, in ensure_joined
úno 01 22:28:16 bolesiny.net python[1631053]:     raise IntentError(f"Failed to join room {room_id} as {self.mxid}") from e
úno 01 22:28:16 bolesiny.net python[1631053]: mautrix.errors.base.IntentError: Failed to join room !LXGMQQxZTcJOqPivZC:bolesiny.net as @facebookbot:bolesiny.net
```

Room !LXGMQQxZTcJOqPivZC no longer exists within my synapse server, but mautrix-facebook has a reference to it...
![obrazek](https://user-images.githubusercontent.com/15554561/106524150-73049a00-64e2-11eb-8d00-f89032ac9fcd.png)

Not sure what membership=leave means.
How to fix it?

Thanks

**Comment by waclaw66** [comment]
I have solved that deleting that room from mx_user_profile table and set the right room to notice_room within users table.
I'm not sure when it messed up, probably while migrating to 2.0. Now it works flawlessly.
