### ISSUE TITLE
Notice room is not updated

### ISSUE THREAD

**Issue by waclaw66** [tulir/mautrix-facebook#149]
When a room with facebookbot is left and new created, `notice_room` is not updated within `user` table with new room id.
mautrix-facebook then fails with following message...
```
python[1799162]: [2021-04-15 21:21:16,444] [WARNING@mau.user.@waclaw:bolesiny.net] Failed to send bridge notice
python[1799162]: Traceback (most recent call last):
python[1799162]:   File "/opt/mautrix-facebook/lib/python3.9/site-packages/mautrix/appservice/api/intent.py", line 335, in ensure_joined
python[1799162]:     await self.join_room(room_id, max_retries=0)
python[1799162]:   File "/opt/mautrix-facebook/lib/python3.9/site-packages/mautrix/appservice/api/intent.py", line 83, in wrapper
python[1799162]:     return await __method(*args, **kwargs)
python[1799162]:   File "/opt/mautrix-facebook/lib/python3.9/site-packages/mautrix/client/api/rooms.py", line 252, in join_room
python[1799162]:     content = await self.api.request(Method.POST, Path.join[room_id_or_alias],
python[1799162]:   File "/opt/mautrix-facebook/lib/python3.9/site-packages/mautrix/api.py", line 233, in request
python[1799162]:     return await self._send(method, full_url, content, query_params, headers or {})
python[1799162]:   File "/opt/mautrix-facebook/lib/python3.9/site-packages/mautrix/api.py", line 158, in _send
python[1799162]:     raise make_request_error(http_status=response.status,
python[1799162]: mautrix.errors.request.MUnknown: No known servers
python[1799162]: The above exception was the direct cause of the following exception:
python[1799162]: Traceback (most recent call last):
python[1799162]:   File "/opt/mautrix-facebook/lib/python3.9/site-packages/mautrix_facebook/user.py", line 487, in send_bridge_notice
python[1799162]:     event_id = await self.az.intent.send_message(await self.get_notice_room(), content)
python[1799162]:   File "/opt/mautrix-facebook/lib/python3.9/site-packages/mautrix/appservice/api/intent.py", line 94, in wrapper
python[1799162]:     await __self.ensure_joined(room_id)
python[1799162]:   File "/opt/mautrix-facebook/lib/python3.9/site-packages/mautrix/appservice/api/intent.py", line 357, in ensure_joined
python[1799162]:     raise IntentError(f"Failed to join room {room_id} as {self.mxid}") from e
python[1799162]: mautrix.errors.base.IntentError: Failed to join room !lFfLUtWrHDnMaDiohy:bolesiny.net as @facebookbot:bolesiny.net
```

**Comment by Paragoumba** [comment]
Can reproduce. I updated the notice room by sending `set-notice-room` in the new room.
