### ISSUE TITLE
Mautrix-facebook fails to start

### ISSUE THREAD

**Issue by deyanyosifov** [tulir/mautrix-facebook#151]
I am trying to set up the mautrix-facebook bridge. I follow the guide, all installation steps seem to be successful but when I try to start the bridge with python -m mautrix_facebook I get the following error:
```
(mautrix-facebook) ****@****:~/mautrix-facebook$ python -m mautrix_facebook
[2021-04-18 23:13:28,795] [INFO@mau.init] Initializing mautrix-facebook 0.2.1
[2021-04-18 23:13:28,800] [CRITICAL@mau.init] Unexpected error in initialization
Traceback (most recent call last):
  File "/home/****/mautrix-facebook/lib/python3.8/site-packages/mautrix/util/program.py", line 93, in _prepare
    self.prepare()
  File "/home/****/mautrix-facebook/lib/python3.8/site-packages/mautrix/bridge/bridge.py", line 82, in prepare
    self.prepare_bridge()
  File "/home/****/mautrix-facebook/lib/python3.8/site-packages/mautrix_facebook/__main__.py", line 64, in prepare_bridge
    super().prepare_bridge()
  File "/home/****/mautrix-facebook/lib/python3.8/site-packages/mautrix/bridge/bridge.py", line 146, in prepare_bridge
    self.matrix = self.matrix_class(bridge=self)
  File "/home/****/mautrix-facebook/lib/python3.8/site-packages/mautrix_facebook/matrix.py", line 36, in __init__
    prefix, suffix = bridge.config["bridge.username_template"].format(userid=":").split(":")
ValueError: not enough values to unpack (expected 2, got 1)
```

What could be the problem?

**Comment by tulir** [comment]
That sounds like you messed up something in `bridge.username_template`

**Comment by deyanyosifov** [comment]
I haven't touched this file (bridge.username_template) at all, there's not even such a file on my system (I searched with locate). I tried a second time in a new directory, installation proceeds without errors but when I try to start it, I get the same error. I tried installing another bridge (mautrix-twitter) - the same result with the same error. Do you have any clue? Could I have messed something in the config.yaml file? Synapse itself runs without any problems, including federation.

**Comment by tulir** [comment]
`bridge.username_template` means the `bridge` -> `username_template` in `config.yaml`

**Comment by deyanyosifov** [comment]
It's username_template: facebook_101569205415638768 (I have just changed a few digits because I don't want to disclose my facebook ID). Is the format wrong somehow?

**Comment by tulir** [comment]
Yes, it's a template, the `{userid}` placeholder is required.
