### ISSUE TITLE
Errors when upgrading v0.1.2 -> v0.2.1

### ISSUE THREAD

**Issue by 3nprob** [tulir/mautrix-facebook#154]
When upgrading from v.0.1.2 to v0.2.1 (postgresql, config file on read-only filesystem):

```
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
Failed to overwrite the config in /data/config.yaml
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/mautrix/util/config/file.py", line 49, in save
    with open(self.path, 'w') as stream:
PermissionError: [Errno 13] Permission denied: '/data/config.yaml'
[2021-04-27 01:53:39,439] [INFO@mau.init] Initializing mautrix-facebook 0.2.1
[2021-04-27 01:53:39,443] [INFO@mau.init] Initialization complete in 0.14 seconds
[2021-04-27 01:53:39,444] [DEBUG@mau.init] Running startup actions...
[2021-04-27 01:53:39,444] [DEBUG@mau.db] Connecting to postgres://xxxxx@yyyy/zzzz
[2021-04-27 01:53:39,488] [DEBUG@mau.db.upgrade] Upgrading database from v0 to v1: Initial asyncpg revision
[2021-04-27 01:53:48,553] [DEBUG@mau.client.db.upgrade] Upgrading matrix state cache from v0 to v1: Initial revision
[2021-04-27 01:53:48,568] [DEBUG@mau.client.db.upgrade] Upgrading matrix state cache from v1 to v2: Stop using size-limited string fields
[2021-04-27 01:53:48,595] [DEBUG@mau.init] Starting appservice...
[2021-04-27 01:53:48,596] [DEBUG@mau.as] Starting appservice web server on 0.0.0.0:22933
[2021-04-27 01:53:48,597] [INFO@mau.mx] Ensuring connectivity to homeserver
[2021-04-27 01:53:48,642] [DEBUG@mau.bridge.e2ee] Logging in with bridge bot user
[2021-04-27 01:53:48,658] [DEBUG@mau.bridge.e2ee] Found device ID in database: REDACTED
[2021-04-27 01:53:48,786] [INFO@mau.bridge.e2ee] End-to-bridge encryption support is enabled
[2021-04-27 01:53:48,788] [DEBUG@mau.mx] Initializing appservice bot
[2021-04-27 01:53:48,805] [ERROR@mau.puppet.701962552] Failed to initialize custom mxid
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/mautrix/api.py", line 238, in request
    return await self._send(method, full_url, content, query_params, headers or {})
  File "/usr/lib/python3.8/site-packages/mautrix/api.py", line 154, in _send
    async with request as response:
  File "/usr/lib/python3.8/site-packages/aiohttp/client.py", line 1117, in __aenter__
    self._resp = await self._coro
  File "/usr/lib/python3.8/site-packages/aiohttp/client.py", line 492, in _request
    req = self._request_class(
  File "/usr/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 305, in __init__
    self.update_host(url)
  File "/usr/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 366, in update_host
    raise InvalidURL(url)
aiohttp.client_exceptions.InvalidURL: /None/_matrix/client/r0/account/whoami

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/mautrix/bridge/custom_puppet.py", line 217, in try_start
    await self.start(retry_auto_login=retry_auto_login)
  File "/usr/lib/python3.8/site-packages/mautrix/bridge/custom_puppet.py", line 228, in start
    mxid = await self.intent.whoami()
  File "/usr/lib/python3.8/site-packages/mautrix/client/api/authentication.py", line 154, in whoami
    resp = await self.api.request(Method.GET, Path.account.whoami)
  File "/usr/lib/python3.8/site-packages/mautrix/api.py", line 240, in request
    raise MatrixConnectionError(str(e)) from e
mautrix.errors.base.MatrixConnectionError: /None/_matrix/client/r0/account/whoami
[2021-04-27 01:53:48,840] [DEBUG@mau.bridge.e2ee.client] Starting syncing
```

Config subset:

```
homeserver:
    address: http://REDACTED
    domain: example.com
    verify_ssl: false

appservice:
    address: http://127.0.0.1:22933
    hostname: 0.0.0.0
    port: 22933
    max_body_size: 3
    database: postgres://REDACTED@REDACTED/REDACTED
    public:
        enabled: true
        prefix: /public
        external: https://facebookbridge.int.example.com/public
        shared_secret: ""
    id: facebook
    bot_username: facebookbot
    bot_displayname: Facebook bridge bot
    bot_avatar: mxc://maunium.net/ddtNPZSKMNqaUzqrHuWvUADv
    community_id: +facebook:example.com
    as_token: "REDACTED"
    hs_token: "REDACTED"


bridge:
    username_template: "facebook_{userid}"
    community_template: facebook_{localpart}={server}
    displayname_template: "{displayname} [FB] ({name})"
    displayname_preference:
    - name

    command_prefix: "!fb"

    initial_chat_sync: 5000
    invite_own_puppet_to_pm: true
    sync_with_custom_puppets: true
    login_shared_secret: "REDACTED"
    presence: true
    update_avatar_initial_sync: true
    encryption:
        allow: true
        default: true
        database: default
        key_sharing:
          allow: true
          require_cross_signing: true
          require_verification: true
    delivery_receipts: false
    allow_invites: false
    backfill:
        invite_own_puppet: true
        initial_limit: 1000000
        missed_limit: 1000000
        disable_notifications: false
    periodic_reconnect:
        interval: 7200
        mode: refresh
        always: true
    resync_max_disconnected_time: 5
    temporary_disconnect_notices: false
    refresh_on_reconnection_fail: true
    resend_bridge_info: false

    permissions:
        "example.com": "user"
        "@admin:example.com": "admin"
```

I changed the following in config before upgrading:

```
appservice.public.enabled: false -> true
appservice.public.external: [default value] -> [custom url]
```

**Comment by 3nprob** [comment]
Allowing write to config.yml and addressing the differences, it still tries to write to it (despite all values being equal).

The `Failed to initialize custom mxid` resulting from `aiohttp.client_exceptions.InvalidURL: /None/_matrix/client/r0/account/whoami
` is still present  in any case.

**Comment by tulir** [comment]
That's an old bug that happened before v0.2.0, you can fix it with `UPDATE puppet SET base_url=null;`
