### ISSUE TITLE
Getting duplicate messages on matrix after upgrade

### ISSUE THREAD

**Issue by baltitenger** [tulir/mautrix-facebook#155]
Almost all messages are arriving twice to matrix after I upgraded from 79e0760 to 9ff891e (also upgraded mautrix-python from 0.8.18 to 0.9.1)
With each duplicate message, I get the following log:
```
[2021-04-29 23:41:13,765] [INFO@aiohttp.access] ::1 [29/Apr/2021:21:41:13 +0000] "PUT /transactions/560881?access_token=iBst3UdX-yslbK5gi_gYRD6QCjxNkphYXw-hzrUBQkFlGv3A1BTGhM0FDU0x2IFz HTTP/1.1" 200 158 "-" "Synapse/1.28.0"
[2021-04-29 23:41:14,015] [INFO@aiohttp.access] ::1 [29/Apr/2021:21:41:14 +0000] "PUT /transactions/560882?access_token=iBst3UdX-yslbK5gi_gYRD6QCjxNkphYXw-hzrUBQkFlGv3A1BTGhM0FDU0x2IFz HTTP/1.1" 200 158 "-" "Synapse/1.28.0"
[2021-04-29 23:41:14,073] [DEBUG@mau.portal.3478453708891533] Handled Messenger message mid.$gAAxbop2vpY1_UNlsWF5H5QhQuCzN -> ['$mMK-8yveHUTzePCxODFQWtVawQijZ_B9aHNnEMQBUEo']
[2021-04-29 23:41:14,080] [ERROR@mau.portal.3478453708891533] Error handling Facebook message mid.$gAAxbop2vpY1_UNlsWF5H5QhQuCzN
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/mautrix_facebook/portal.py", line 771, in handle_facebook_message
    await self._handle_facebook_message(source, sender, message, reply_to)
  File "/usr/lib/python3.9/site-packages/mautrix_facebook/portal.py", line 845, in _handle_facebook_message
    await DBMessage.bulk_create(fbid=msg_id, oti=oti, fb_chat=self.fbid, fb_sender=sender.fbid,
  File "/usr/lib/python3.9/site-packages/mautrix_facebook/db/message.py", line 108, in bulk_create
    await conn.copy_records_to_table("message", records=records, columns=columns)
  File "/usr/lib/python3.9/site-packages/asyncpg/connection.py", line 923, in copy_records_to_table
    return await self._copy_in_records(
  File "/usr/lib/python3.9/site-packages/asyncpg/connection.py", line 1048, in _copy_in_records
    return await self._protocol.copy_in(
  File "asyncpg/protocol/protocol.pyx", line 506, in copy_in
asyncpg.exceptions.UniqueViolationError: duplicate key value violates unique constraint "message_fbid_fb_receiver_index_key"
DETAIL:  Key (fbid, fb_receiver, index)=(mid.$gAAxbop2vpY1_UNlsWF5H5QhQuCzN, 0, 0) already exists.
```
Note that in this chat, I have two matrix accounts. Also, downgrading did fix the issue.

**Comment by baltitenger** [comment]
Seems to be fixed now, thanks
