### ISSUE TITLE
ValueError: Invalid IPv6 URL

### ISSUE THREAD

**Issue by HammyHavoc** [tulir/mautrix-facebook#166]
Any ideas on where to start digging with this? I'm not using IPv6.

`2021-07-22 03:43:07,384] [[37;1m[41mCRITICAL[0m@[32mmau.init[0m] Unexpected error in main event loop
Traceback (most recent call last):
File "/usr/lib/python3.9/site-packages/mautrix/util/program.py", line 190, in _run
self.loop.run_until_complete(self.start())
File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
return future.result()
File "/usr/lib/python3.9/site-packages/mautrix_facebook/__main__.py", line 90, in start
await self.db.start()
File "/usr/lib/python3.9/site-packages/mautrix/util/async_db/database.py", line 66, in start
self._pool = await asyncpg.create_pool(self.url, **self.db_args)
File "/usr/lib/python3.9/site-packages/asyncpg/pool.py", line 407, in _async__init__
await self._initialize()
File "/usr/lib/python3.9/site-packages/asyncpg/pool.py", line 435, in _initialize
await first_ch.connect()
File "/usr/lib/python3.9/site-packages/asyncpg/pool.py", line 127, in connect
self._con = await self._pool._get_new_connection()
File "/usr/lib/python3.9/site-packages/asyncpg/pool.py", line 477, in _get_new_connection
con = await connection.connect(
File "/usr/lib/python3.9/site-packages/asyncpg/connection.py", line 1981, in connect
return await connect_utils._connect(
File "/usr/lib/python3.9/site-packages/asyncpg/connect_utils.py", line 725, in _connect
addrs, params, config = _parse_connect_arguments(timeout=timeout, **kwargs)
File "/usr/lib/python3.9/site-packages/asyncpg/connect_utils.py", line 491, in _parse_connect_arguments
addrs, params = _parse_connect_dsn_and_args(
File "/usr/lib/python3.9/site-packages/asyncpg/connect_utils.py", line 231, in _parse_connect_dsn_and_args
parsed = urllib.parse.urlparse(dsn)
File "/usr/lib/python3.9/urllib/parse.py", line 393, in urlparse
splitresult = urlsplit(url, scheme, allow_fragments)
File "/usr/lib/python3.9/urllib/parse.py", line 482, in urlsplit
raise ValueError("Invalid IPv6 URL")
ValueError: Invalid IPv6 URL`

**Comment by HammyHavoc** [comment]
Password had special characters in it, encoded it.

**Comment by JuniorJPDJ** [comment]
what was the problem? what was the solution?

**Comment by HammyHavoc** [comment]
The problem was special characters (punctuation/symbols) in my password in the config for the database. I encoded it and it worked without issue.
________________________________
