### ISSUE TITLE
Failed to sync threads on first sync

### ISSUE THREAD

**Issue by turt2live** [tulir/mautrix-facebook#18]
```
[2019-05-15 04:23:39,140] [ERROR@mau.user.@travis:t2l.io] Failed to sync threads
Traceback (most recent call last):
  File "/home/facebook/mautrix-facebook/mautrix_facebook/user.py", line 155, in sync_threads
    await portal.create_matrix_room(self, thread)
  File "/home/facebook/mautrix-facebook/mautrix_facebook/portal.py", line 243, in create_matrix_room
    await self._create_matrix_room(source, info)
  File "/home/facebook/mautrix-facebook/mautrix_facebook/portal.py", line 251, in _create_matrix_room
    info = await self.update_info(source=source, info=info)
  File "/home/facebook/mautrix-facebook/mautrix_facebook/portal.py", line 173, in update_info
    loop=self.loop))
  File "/home/facebook/mautrix-facebook/mautrix_facebook/portal.py", line 219, in _update_participants
    await p.Puppet.get_by_fbid(info.uid).update_info(source=source, info=info)
  File "/home/facebook/mautrix-facebook/mautrix_facebook/puppet.py", line 133, in update_info
    loop=self.loop))
  File "/home/facebook/mautrix-facebook/mautrix_facebook/puppet.py", line 151, in _update_photo
    self.default_mxid_intent)
  File "/home/facebook/mautrix-facebook/mautrix_facebook/portal.py", line 192, in _reupload_fb_photo
    return await intent.upload_media(data, mime_type=mime, filename=filename), mime, len(data)
  File "/home/facebook/fbenv/lib/python3.6/site-packages/mautrix/client/api/modules/media_repository.py", line 54, in upload_media
    headers=headers, query_params=query)
  File "/home/facebook/fbenv/lib/python3.6/site-packages/mautrix/api/http.py", line 206, in request
    return await self._send(method, endpoint, content, query_params, headers or {})
  File "/home/facebook/fbenv/lib/python3.6/site-packages/mautrix/api/http.py", line 146, in _send
    errcode=errcode, message=message)
mautrix.errors.request.MUnknown: Unexpected Error
```

**Comment by bobpaul** [comment]
I get a very similar error every time I issue `!fb sync`:

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/mautrix/bridge/commands/handler.py", line 359, in handle
    await self._run_handler(handler, evt)
  File "/usr/lib/python3.8/site-packages/mautrix/bridge/commands/handler.py", line 253, in __call__
    return await self._handler(evt)
  File "/usr/lib/python3.8/site-packages/mautrix_facebook/commands/facebook.py", line 68, in sync
    threads = await evt.sender.fetch_threads(limit=limit, thread_location=ThreadLocation.INBOX)
  File "/usr/lib/python3.8/site-packages/fbchat/_client.py", line 269, in fetch_threads
    candidates = await self.fetch_thread_list(
  File "/usr/lib/python3.8/site-packages/fbchat/_client.py", line 780, in fetch_thread_list
    rtn.append(Group._from_graphql(node))
  File "/usr/lib/python3.8/site-packages/fbchat/_group.py", line 39, in _from_graphql
    int(data["last_message"]["nodes"][0]["timestamp_precise"])
IndexError: list index out of range
```
seen on rev 0a972cd

**Comment by tulir** [comment]
This probably doesn't apply anymore
