### ISSUE TITLE
Can't specify base config from command line

### ISSUE THREAD

**Issue by turt2live** [tulir/mautrix-facebook#23]
eg:
```
/home/facebook/fbenv/bin/python -m mautrix_facebook -c /home/facebook/config.yaml -b /home/facebook/mautrix_facebook/example-config.yaml
```

results in:
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/facebook/fbenv/lib/python3.6/site-packages/mautrix_facebook/__main__.py", line 62, in <module>
    MessengerBridge().run()
  File "/home/facebook/fbenv/lib/python3.6/site-packages/mautrix/bridge/bridge.py", line 84, in run
    self._prepare()
  File "/home/facebook/fbenv/lib/python3.6/site-packages/mautrix/bridge/bridge.py", line 90, in _prepare
    self.prepare_config(args.config, args.registration, args.base_config)
  File "/home/facebook/fbenv/lib/python3.6/site-packages/mautrix/bridge/bridge.py", line 105, in prepare_config
    self.config.update()
  File "/home/facebook/fbenv/lib/python3.6/site-packages/mautrix/util/config.py", line 138, in update
    raise ValueError("Can't update() without base config")
ValueError: Can't update() without base config
```

**Comment by turt2live** [comment]
Turns out I just fail at copy/pasting paths - works fine.
