### ISSUE TITLE
Error when trying to log in using 2FA

### ISSUE THREAD

**Issue by Munfred** [tulir/mautrix-facebook#31]
I set up a homeserver using the ansible playbook and the `:latest` docker image and tried using 2FA to log in (after failing repeatedly due to "new location sign in")

```
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/mautrix/bridge/commands/handler.py", line 366, in handle
    await handler(evt)
  File "/usr/lib/python3.7/site-packages/mautrix/bridge/commands/handler.py", line 267, in __call__
    return await self._handler(evt)
  File "/opt/mautrix-facebook/mautrix_facebook/commands/auth.py", line 40, in login
    await evt.sender.login(evt.args[0], " ".join(evt.args[1:]), max_tries=1)
  File "/usr/lib/python3.7/site-packages/fbchat/_client.py", line 272, in login
    log=self._state_log
  File "/usr/lib/python3.7/site-packages/fbchat/_state.py", line 133, in login
    resp = await _2fa_helper(session, code, resp, log)
  File "/usr/lib/python3.7/site-packages/fbchat/_state.py", line 28, in _2fa_helper
    soup = find_input_fields(r.text)
  File "/usr/lib/python3.7/site-packages/fbchat/_state.py", line 18, in find_input_fields
    return bs4.BeautifulSoup(html, "html.parser", parse_only=bs4.SoupStrainer("input"))
  File "/usr/lib/python3.7/site-packages/bs4/__init__.py", line 246, in __init__
    elif len(markup) <= 256 and (
TypeError: object of type 'method' has no len()
```
![image](https://user-images.githubusercontent.com/12504176/62450911-16c08e80-b722-11e9-8a48-1c1342d8cace.png)

**Comment by tulir** [comment]
I think this was fixed already
