### ISSUE TITLE
Unhandled error when trying to sync MARKETPLACE Thread

### ISSUE THREAD

**Issue by Rafaeltheraven** [tulir/mautrix-facebook#33]
After some messing around, I got the bridge up and running. However, after calling `!fb sync` for the first time, I was greeted by the following code block:

```
Traceback (most recent call last):
  File "/home/rafael/webservices/matrix/mautrix-facebook/lib/python3.7/site-packages/mautrix/bridge/commands/handler.py", line 371, in handle
    await self._run_handler(handler, evt)
  File "/home/rafael/webservices/matrix/mautrix-facebook/lib/python3.7/site-packages/mautrix/bridge/commands/handler.py", line 269, in __call__
    return await self._handler(evt)
  File "/home/rafael/webservices/matrix/mautrix-facebook/lib/python3.7/site-packages/mautrix_facebook/commands/facebook.py", line 68, in sync
    threads = await evt.sender.fetchThreads(limit=limit, thread_location=ThreadLocation.INBOX)
  File "/home/rafael/webservices/matrix/mautrix-facebook/lib/python3.7/site-packages/fbchat/_client.py", line 380, in fetchThreads
    before=last_thread_timestamp, thread_location=thread_location
  File "/home/rafael/webservices/matrix/mautrix-facebook/lib/python3.7/site-packages/fbchat/_client.py", line 903, in fetchThreadList
    "Unknown thread type: {}, with data: {}".format(_type, node)
fbchat._exception.FBchatException: Unknown thread type: MARKETPLACE, with data: {REDACTED}
```

This is for a Marktetplace chat. I think you might have simply forgotten that those exist?

**Comment by JuniorJPDJ** [comment]
It would be nice if you could use this chats through bridge

**Comment by tulir** [comment]
This no longer applies, open a new issue with new logs if there are similar issues
