### ISSUE TITLE
Logging in fails 

### ISSUE THREAD

**Issue by Philantrop** [tulir/mautrix-facebook#34]
I followed the [Production setup](https://github.com/tulir/mautrix-facebook/wiki/Bridge-setup#production-setup) procedure and tried logging in using the "login" command which failed with the following traceback:

```
Logging in...
Unhandled error while handling command:
Traceback (most recent call last):
  File "/var/lib/synapse/mautrix-facebook/lib/python3.7/site-packages/mautrix/bridge/commands/handler.py", line 371, in handle
    await self._run_handler(handler, evt)
  File "/var/lib/synapse/mautrix-facebook/lib/python3.7/site-packages/mautrix/bridge/commands/handler.py", line 269, in __call__
    return await self._handler(evt)
  File "/var/lib/synapse/mautrix-facebook/lib/python3.7/site-packages/mautrix_facebook/commands/auth.py", line 60, in login
    user_agent=evt.sender.user_agent)
  File "/var/lib/synapse/mautrix-facebook/lib/python3.7/site-packages/fbchat/_client.py", line 274, in login
    log=self._state_log
  File "/var/lib/synapse/mautrix-facebook/lib/python3.7/site-packages/fbchat/_state.py", line 140, in login
    return await cls.from_session(session=session)
  File "/var/lib/synapse/mautrix-facebook/lib/python3.7/site-packages/fbchat/_state.py", line 183, in from_session
    revision = int(text.split('"client_revision":', 1)[1].split(",", 1)[0])
IndexError: list index out of range

```

**Comment by tyleradams** [comment]
^ I hit the same issue.

**Comment by Philantrop** [comment]
@tyleradams: The "[login-cookie flow](https://github.com/tulir/mautrix-facebook/wiki/Authentication)" makes it work. You do NOT have to enable 2FA before you authenticate like that.
