### ISSUE TITLE
Python 3.8 or other Problem @Startup

### ISSUE THREAD

**Issue by DoM1niC** [tulir/mautrix-facebook#38]
Since Python 3.8

requirements are installed and running in virtualenv, Matrix itself works fine after Upgrade to Python 3.8+
```
[2019-12-01 18:10:35,167] [CRITICAL@mau.init] Unexpected error in initialization
Traceback (most recent call last):
  File "/home/projects/python/.matrix-facebook/lib/python3.8/site-packages/mautrix/bridge/bridge.py", line 112, in _prepare
    self.prepare_bridge()
  File "/home/projects/python/.matrix-facebook/mautrix_facebook/__main__.py", line 46, in prepare_bridge
    self.matrix = context.mx = MatrixHandler(context)
  File "/home/projects/python/.matrix-facebook/mautrix_facebook/matrix.py", line 34, in __init__
    super().__init__(context.az, context.config, command_processor=c.CommandProcessor(context))
  File "/home/projects/python/.matrix-facebook/mautrix_facebook/commands/handler.py", line 76, in __init__
    super().__init__(az=context.az, config=context.config, event_class=CommandEvent,
TypeError: __init__() missing 1 required positional argument: 'bridge'
(.matrix-facebook) python@webapps:~/.matrix-facebook$

```

**Comment by tulir** [comment]
Not related to python, just a breaking change in a library. Should work now
