### ISSUE TITLE
Error when bridging voice messages

### ISSUE THREAD

**Issue by spantaleev** [tulir/mautrix-facebook#40]
Ever since the MQTT changes (supposedly), voice message bridging fails.

Here are some logs:

```
[2020-01-05 13:31:25,030] [DEBUG@mau.as.api.@facebook_11111111111111111111:example.com] POST /_matrix/media/r0/upload <199343 bytes>
[2020-01-05 13:31:25,061] [ERROR@mau.user.@user:example.com] Failed to parse MQTT message: {'deltas': [{'attachments': [{'fbid': '22222222222', 'fileSize': '199343', 'filename': 'audioclip-33333333333333-24002.aac', 'genericMetadata': {'duration': '24002', 'isVoicemail': '0', 'type': 'fb_voice_message', 'call_id': ''}, 'hash': '22222222222', 'id': '22222222222', 'mercury': {'blob_attachment': {'__typename': 'MessageAudio', 'attribution_app': None, 'attribution_metadata': None, 'filename': 'audioclip-33333333333333-24002.aac', 'playable_url': '.....', 'playable_duration_in_ms': 24002, 'is_voicemail': False, 'audio_type': 'VOICE_MESSAGE', 'url_shimhash': '......', 'url_skipshim': True}}, 'mimeType': 'audio/aac', 'otherUserFbIds': ['444444444'], 'titanType': 6, 'useRefCounting': True}], 'irisSeqId': '55555555', 'irisTags': ['DeltaNewMessage', 'is_from_iris_fanout'], 'messageMetadata': {'actorFbId': '11111111111111111111', 'folderId': {'systemFolderId': 'INBOX'}, 'messageId': 'mid.$cBBBa3B...', 'offlineThreadingId': '66666666666666', 'skipBumpThread': False, 'skipSnippetUpdate': False, 'tags': ['source:titan:orca', 'app_id:7777777777777'], 'threadKey': {'otherUserFbId': '11111111111111111111'}, 'threadReadStateEffect': 'MARK_UNREAD', 'timestamp': '1578231084710', 'unsendType': 'deny_for_non_sender'}, 'requestContext': {'apiArgs': {}}, 'class': 'NewMessage'}], 'firstDeltaSeqId': 55555555, 'lastIssuedSeqId': 55555555, 'queueEntityId': 444444444}
Traceback (most recent call last):
File "/usr/lib/python3.7/site-packages/fbchat/_client.py", line 2875, in _try_parse_mqtt
await self._parse_mqtt(event_type, event_data)
File "/usr/lib/python3.7/site-packages/fbchat/_client.py", line 2893, in _parse_mqtt
await self._parse_delta({"delta": delta})
File "/usr/lib/python3.7/site-packages/fbchat/_client.py", line 2609, in _parse_delta
msg=m,
File "/opt/mautrix-facebook/mautrix_facebook/user.py", line 363, in on_message
await portal.handle_facebook_message(self, puppet, message_object)
File "/opt/mautrix-facebook/mautrix_facebook/portal.py", line 502, in handle_facebook_message
for attachment in message.attachments])
File "/opt/mautrix-facebook/mautrix_facebook/portal.py", line 555, in _handle_facebook_attachment
relates_to=self._get_facebook_reply(reply_to))
File "/usr/lib/python3.7/site-packages/mautrix/appservice/api/intent.py", line 87, in wrapper
return await __method(*args, **kwargs)
File "/usr/lib/python3.7/site-packages/mautrix/appservice/api/intent.py", line 289, in send_message_event
return await super().send_message_event(room_id, event_type, content, **kwargs)
File "/usr/lib/python3.7/site-packages/mautrix/client/api/events.py", line 294, in send_message_event
resp = await self.api.request(Method.PUT, url, content, **kwargs)
File "/usr/lib/python3.7/site-packages/mautrix/api/http.py", line 199, in request
content = json.dumps(content)
File "/usr/lib/python3.7/json/__init__.py", line 231, in dumps
return _default_encoder.encode(obj)
File "/usr/lib/python3.7/json/encoder.py", line 199, in encode
chunks = self.iterencode(o, _one_shot=True)
File "/usr/lib/python3.7/json/encoder.py", line 257, in iterencode
return _iterencode(o, 0)
File "/usr/lib/python3.7/json/encoder.py", line 179, in default
raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type timedelta is not JSON serializable
```

**Comment by tulir** [comment]
This is reportedly fixed since the fbchat update
