### ISSUE TITLE
ValueError: too many values to unpack (expected 1)

### ISSUE THREAD

**Issue by IngwiePhoenix** [tulir/mautrix-facebook#44]
Hey there!

I am by far not a snake guy so... I have some difficulties understanding what Python is trying to tell me here?

Basically, I logged in using the cookie method and then ran `sync`. And then, this happened:

```
Traceback (most recent call last):
  File "/srv/matrix/facebook/lib/python3.7/site-packages/mautrix/bridge/commands/handler.py", line 359, in handle
    await self._run_handler(handler, evt)
  File "/srv/matrix/facebook/lib/python3.7/site-packages/mautrix/bridge/commands/handler.py", line 253, in __call__
    return await self._handler(evt)
  File "/srv/matrix/facebook/lib/python3.7/site-packages/mautrix_facebook/commands/facebook.py", line 68, in sync
    threads = await evt.sender.fetch_threads(limit=limit, thread_location=ThreadLocation.INBOX)
  File "/srv/matrix/facebook/lib/python3.7/site-packages/fbchat/_client.py", line 270, in fetch_threads
    before=last_thread_dt, thread_location=thread_location
  File "/srv/matrix/facebook/lib/python3.7/site-packages/fbchat/_client.py", line 774, in fetch_thread_list
    j, = await self.graphql_requests(_graphql.from_doc_id("1349387578499440", params))
  File "/srv/matrix/facebook/lib/python3.7/site-packages/fbchat/_client.py", line 135, in graphql_requests
    util_log=self._util_log))
  File "/srv/matrix/facebook/lib/python3.7/site-packages/fbchat/_state.py", line 313, in _graphql_requests
    req_log=req_log, util_log=util_log)
  File "/srv/matrix/facebook/lib/python3.7/site-packages/fbchat/_state.py", line 285, in _post
    resp = _graphql.response_to_json(content)
  File "/srv/matrix/facebook/lib/python3.7/site-packages/fbchat/_graphql.py", line 51, in response_to_json
    [(key, value)] = x.items()
ValueError: too many values to unpack (expected 1)
```

How do I fix that? o.o

Kind regards,
Ingwie

**Comment by christianlupus** [comment]
I can confirm this on my (test) installation as well.
I use a separate matrix community to keep the room list neat. In the community all (?) of my facebook friends are present but none of the chats.

**Comment by christianlupus** [comment]
I now got it working. It seems that facebook wanted to proterct my from myself. I was logged out on all devices and had to reset my password. After doing so and relogin in matrix bridge, the synchronization worked.

@IngwiePhoenix Could you check if you are still logged in in the main browser and do a logout login in matrix?
