### ISSUE TITLE
login-cookie not working

### ISSUE THREAD

**Issue by bobpaul** [tulir/mautrix-facebook#48]
after upgrading to 9264125, `login-cookie` isn't work. 

```
Apr 11 21:52:12 archlinux mautrix-facebook[407738]: [2020-04-11 21:52:12,425] [INFO@aiohttp.access] 127.0.0.1 [11/Apr/2020:21:52:12 +0000] "PUT /transactions/350?access_token=SNIP HTTP/1.1" 200 158 "-" "Synapse/1.11.1"
Apr 11 21:52:14 archlinux mautrix-facebook[407738]: [2020-04-11 21:52:14,226] [ERROR@fbchat.client.@SNIP:SNIP] Failed loading session
Apr 11 21:52:14 archlinux mautrix-facebook[407738]: Traceback (most recent call last):
Apr 11 21:52:14 archlinux mautrix-facebook[407738]:   File "/usr/lib/python3.8/site-packages/fbchat/_client.py", line 184, in set_session
Apr 11 21:52:14 archlinux mautrix-facebook[407738]:     self._state = await _state.State.from_cookies(session_cookies, loop=self.loop,
Apr 11 21:52:14 archlinux mautrix-facebook[407738]:   File "/usr/lib/python3.8/site-packages/fbchat/_state.py", line 246, in from_cookies
Apr 11 21:52:14 archlinux mautrix-facebook[407738]:     return await cls.from_session(session=session)
Apr 11 21:52:14 archlinux mautrix-facebook[407738]:   File "/usr/lib/python3.8/site-packages/fbchat/_state.py", line 227, in from_session
Apr 11 21:52:14 archlinux mautrix-facebook[407738]:     user_id, fb_dtsg, revision, logout_h = await cls._from_session(session)
Apr 11 21:52:14 archlinux mautrix-facebook[407738]:   File "/usr/lib/python3.8/site-packages/fbchat/_state.py", line 209, in _from_session
Apr 11 21:52:14 archlinux mautrix-facebook[407738]:     revision = int(text.split('"client_revision":', 1)[1].split(",", 1)[0])
Apr 11 21:52:14 archlinux mautrix-facebook[407738]: IndexError: list index out of range
```

**Comment by ericmigi** [comment]
me too, but with a slightly different error from a mautrix-manager login attempt

```
[2020-04-12 00:36:15,220] [ERROR@aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/usr/lib/python3.8/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/opt/mautrix-facebook/mautrix_facebook/web/public.py", line 134, in login
    return web.json_response({}, status=200, headers=self._headers)
  File "/usr/lib/python3.8/site-packages/aiohttp/web_response.py", line 716, in json_response
    return Response(text=text, body=body, status=status, reason=reason,
  File "/usr/lib/python3.8/site-packages/aiohttp/web_response.py", line 512, in __init__
    raise ValueError("passing both Content-Type header and "
ValueError: passing both Content-Type header and content_type or charset params is forbidden
```

**Comment by aspic** [comment]
Seems to work for me now with the latest patches!

**Comment by thomcatdotrocks** [comment]
Downgrading `fbchat-asyncio` to `0.6.0b2` fixed the issue for me.

**Comment by tulir** [comment]
@thomcatdotrocks Unless Facebook is doing something really weird, I'd assume 0.6.0b2 will break for you soon and only b3 will work

**Comment by tulir** [comment]
fbchat-asyncio 0.6.0 should work with both the new and slightly older formats
