### ISSUE TITLE
Images are not received after pulling latest docker image

### ISSUE THREAD

**Issue by Gr3q** [tulir/mautrix-facebook#55]
Can't receive images after I pulled the docker image (latest) from exiting chats. (I don't know if it happens with new chats)

I'll go through my logs and test a bit when I have some time, in the meantime I open the issue so you know it exist.

**Comment by matejdro** [comment]
This is probably related:

```
[[31;1mERROR[0m@fbchat] An exception occured while reading attachments: [{'fbid': '{REDACTED}', 'fileSize': '269882', 'filename': '{REDACTED}_n.png', 'genericMetadata': {'fbtype': '1586'}, 'hash': '{REDACTED}', 'haystackHandle': '{REDACTED}::', 'id': '{REDACTED}', 'imageMetadata': {'height': 978, 'width': 1500}, 'mercury': {'blob_attachment': {'__typename': 'MessageImage', 'attribution_app': None, 'attribution_metadata': None, 'filename': 'image-{REDACTED}', 'preview': {'uri': '{REDACTED}', 'height': 480, 'width': 736}, 'thumbnail': {'uri': '{REDACTED}'}, 'photo_encodings': [], 'legacy_attachment_id': '{REDACTED}', 'original_dimensions': {'x': 1500, 'y': 978}, 'original_extension': 'png', 'render_as_sticker': False, 'blurred_image_uri': None}}, 'mimeType': 'image/png', 'titanType': 4, 'useRefCounting': True}]
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/fbchat/_models/_message.py", line 433, in _from_pull
    attachment = _file.graphql_to_attachment(
  File "/usr/lib/python3.8/site-packages/fbchat/_models/_file.py", line 177, in graphql_to_attachment
    return ImageAttachment._from_graphql(data)
  File "/usr/lib/python3.8/site-packages/fbchat/_models/_file.py", line 78, in _from_graphql
    previews = {
TypeError: unhashable type: 'Image'
```

**Comment by hooger** [comment]
I experiencing it as well, since #54. Maybe they are related.
