### ISSUE TITLE
Can't sync or receive messages - backfill issue

### ISSUE THREAD

**Issue by Gr3q** [tulir/mautrix-facebook#57]
Error:
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/mautrix/bridge/commands/handler.py", line 359, in handle
    await self._run_handler(handler, evt)
  File "/usr/lib/python3.8/site-packages/mautrix/bridge/commands/handler.py", line 253, in __call__
    return await self._handler(evt)
  File "/usr/lib/python3.8/site-packages/mautrix_facebook/commands/facebook.py", line 78, in sync
    await portal.backfill(evt.sender, is_initial=False, last_active=thread.last_active)
  File "/usr/lib/python3.8/site-packages/mautrix_facebook/portal.py", line 959, in backfill
    elif last_active and most_recent.date >= last_active:
TypeError: can't compare offset-naive and offset-aware datetimes
```

**Comment by tulir** [comment]
Backfilling doesn't currently support SQLite
