### ISSUE TITLE
User not registered on startup

### ISSUE THREAD

**Issue by stuartf** [tulir/mautrix-facebook#60]
I followed the setup document in the wiki, but when I start the bridge I get this stack trace:

    [2020-06-08 10:35:13,810] [INFO@mau.init] Initializing mautrix-facebook 0.1.0rc1
    [2020-06-08 10:35:13,825] [INFO@mau.init] Initialization complete in 0.13 seconds
    [2020-06-08 10:35:13,827] [DEBUG@mau.init] Running startup actions...
    [2020-06-08 10:35:13,827] [DEBUG@mau.init] Starting appservice...
    [2020-06-08 10:35:13,827] [DEBUG@mau.as] Starting appservice web server on 0.0.0.0:29319
    [2020-06-08 10:35:13,828] [INFO@mau.mx] Ensuring connectivity to homeserver
    [2020-06-08 10:35:13,855] [CRITICAL@mau.init] Unexpected error in main event loop
    Traceback (most recent call last):
      File "/opt/mautrix-facebook/venv/lib/python3.7/site-packages/mautrix/util/program.py", line 170, in _run
        self.loop.run_until_complete(self.start())
      File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
        return future.result()
      File "/opt/mautrix-facebook/venv/lib/python3.7/site-packages/mautrix_facebook/__main__.py", line 75, in start
        await super().start()
      File "/opt/mautrix-facebook/venv/lib/python3.7/site-packages/mautrix/bridge/bridge.py", line 125, in start
        await self.matrix.wait_for_connection()
      File "/opt/mautrix-facebook/venv/lib/python3.7/site-packages/mautrix/bridge/matrix.py", line 74, in wait_for_connection
        await self.az.intent.whoami()
      File "/opt/mautrix-facebook/venv/lib/python3.7/site-packages/mautrix/client/api/authentication.py", line 32, in whoami
        resp = await self.api.request(Method.GET, Path.account.whoami)
      File "/opt/mautrix-facebook/venv/lib/python3.7/site-packages/mautrix/api/http.py", line 203, in request
        return await self._send(method, endpoint, content, query_params, headers or {})
      File "/opt/mautrix-facebook/venv/lib/python3.7/site-packages/mautrix/api/http.py", line 145, in _send
        errcode=errcode, message=message)
    mautrix.errors.request.MForbidden: Application service has not registered this user

**Comment by tulir** [comment]
Already fixed on master (with mautrix-python v0.5.2+), will probably make a new bridge release soon
