### ISSUE TITLE
Login-cookie problem

### ISSUE THREAD

**Issue by hooger** [tulir/mautrix-facebook#63]
Tomorrow I missed a couple message and trying the `ping` command I realized that I'm logged out. However, trying login-cookie didn't work. Relevant info from the logs after sending `login-cookie` (and the asked values)
```
Jun 09 14:45:24 matrix matrix-mautrix-facebook[15880]: [2020-06-09 14:45:24,032] [DEBUG@mau.mx] Received Matrix event $###### from @gergely:horvath.club in ######:horvath.club
Jun 09 14:45:24 matrix matrix-mautrix-facebook[15880]: [2020-06-09 14:45:24,086] [INFO@aiohttp.access] 172.20.0.2 [09/Jun/2020:14:45:24 +0000] "PUT /transactions/18114?access_token=###### HTTP/1.1" 200 158 "-" "Synapse/1.14.0"
Jun 09 14:45:27 matrix matrix-mautrix-facebook[15880]: [2020-06-09 14:45:27,485] [INFO@aiohttp.access] 172.20.0.2 [09/Jun/2020:14:45:27 +0000] "PUT /transactions/18115?access_token=###### HTTP/1.1" 200 158 "-" "Synapse/1.14.0"
Jun 09 14:45:36 matrix matrix-mautrix-facebook[15880]: [2020-06-09 14:45:36,831] [DEBUG@mau.mx] Received Matrix event $###### from @gergely:horvath.club in ######:horvath.club
Jun 09 14:45:36 matrix matrix-mautrix-facebook[15880]: [2020-06-09 14:45:36,840] [INFO@aiohttp.access] 172.20.0.2 [09/Jun/2020:14:45:36 +0000] "PUT /transactions/18116?access_token=###### HTTP/1.1" 200 158 "-" "Synapse/1.14.0"
Jun 09 14:45:37 matrix matrix-mautrix-facebook[15880]: [2020-06-09 14:45:37,260] [INFO@aiohttp.access] 172.20.0.2 [09/Jun/2020:14:45:37 +0000] "PUT /transactions/18117?access_token=###### HTTP/1.1" 200 158 "-" "Synapse/1.14.0"
Jun 09 14:45:51 matrix matrix-mautrix-facebook[15880]: [2020-06-09 14:45:51,855] [DEBUG@mau.mx] Received Matrix event $######-UQmU from @gergely:horvath.club in ######:horvath.club
Jun 09 14:45:51 matrix matrix-mautrix-facebook[15880]: [2020-06-09 14:45:51,864] [INFO@aiohttp.access] 172.20.0.2 [09/Jun/2020:14:45:51 +0000] "PUT /transactions/18118?access_token=###### HTTP/1.1" 200 158 "-" "Synapse/1.14.0"
Jun 09 14:45:53 matrix matrix-mautrix-facebook[15880]: [2020-06-09 14:45:53,740] [ERROR@mau.commands] Failed to log in
Jun 09 14:45:53 matrix matrix-mautrix-facebook[15880]: Traceback (most recent call last):
Jun 09 14:45:53 matrix matrix-mautrix-facebook[15880]:   File "/usr/lib/python3.8/site-packages/mautrix_facebook/commands/auth.py", line 123, in enter_login_cookies
Jun 09 14:45:53 matrix matrix-mautrix-facebook[15880]:     session = await fbchat.Session.from_cookies({
Jun 09 14:45:53 matrix matrix-mautrix-facebook[15880]:   File "/usr/lib/python3.8/site-packages/fbchat/_session.py", line 479, in from_cookies
Jun 09 14:45:53 matrix matrix-mautrix-facebook[15880]:     return await cls._from_session(session=session)
Jun 09 14:45:53 matrix matrix-mautrix-facebook[15880]:   File "/usr/lib/python3.8/site-packages/fbchat/_session.py", line 433, in _from_session
Jun 09 14:45:53 matrix matrix-mautrix-facebook[15880]:     raise _exception.NotLoggedIn(
Jun 09 14:45:53 matrix matrix-mautrix-facebook[15880]: fbchat.NotLoggedIn: Found empty fb_dtsg, the session was probably invalid.
Jun 09 14:45:53 matrix matrix-mautrix-facebook[15880]: [2020-06-09 14:45:53,901] [INFO@aiohttp.access] 172.20.0.2 [09/Jun/2020:14:45:53 +0000] "PUT /transactions/18119?access_token=afc78e79-8488-58b6-bb50-6a8f3b3d2398 HTTP/1.1" 200 158 "-" "Synapse/1.14.0"

```

Login also does not work and FB locks my account. Login-cookie does not work but also does not lead to account lock. I have 2FA enabled. Until tomorrow it was working fine. Then there was a restart from cron (not by the appropriate config option, but by calling `systemctl restart service`), and since then, it doesn't work. Restart log:

```
Jun 09 03:23:07 matrix systemd[1]: Starting Matrix Mautrix Facebook server...
Jun 09 03:23:07 matrix matrix-mautrix-facebook[13916]: Error response from daemon: Cannot kill container: matrix-mautrix-facebook: No such container: matrix-mautrix-facebook
Jun 09 03:23:07 matrix matrix-mautrix-facebook[13925]: Error: No such container: matrix-mautrix-facebook
Jun 09 03:23:24 matrix matrix-mautrix-facebook[13935]: INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
Jun 09 03:23:24 matrix matrix-mautrix-facebook[13935]: INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
Jun 09 03:23:37 matrix systemd[1]: Started Matrix Mautrix Facebook server.
Jun 09 03:23:51 matrix matrix-mautrix-facebook[14118]: [2020-06-09 03:23:51,359] [INFO@mau.init] Initializing mautrix-facebook 0.1.0rc1+dev.a6381578
Jun 09 03:23:51 matrix matrix-mautrix-facebook[14118]: [2020-06-09 03:23:51,396] [INFO@mau.init] Initialization complete in 0.57 seconds
Jun 09 03:23:51 matrix matrix-mautrix-facebook[14118]: [2020-06-09 03:23:51,397] [DEBUG@mau.init] Running startup actions...
Jun 09 03:23:51 matrix matrix-mautrix-facebook[14118]: [2020-06-09 03:23:51,397] [DEBUG@mau.init] Starting appservice...
Jun 09 03:23:51 matrix matrix-mautrix-facebook[14118]: [2020-06-09 03:23:51,398] [DEBUG@mau.as] Starting appservice web server on 0.0.0.0:29319
Jun 09 03:23:51 matrix matrix-mautrix-facebook[14118]: [2020-06-09 03:23:51,400] [INFO@mau.mx] Ensuring connectivity to homeserver
Jun 09 03:23:52 matrix matrix-mautrix-facebook[14118]: [2020-06-09 03:23:52,008] [DEBUG@mau.mx] Initializing appservice bot
Jun 09 03:23:52 matrix matrix-mautrix-facebook[14118]: [2020-06-09 03:23:52,023] [INFO@mau.puppet.100001489252999] Initialized custom mxid: @gergely:horvath.club. Starting sync task
Jun 09 03:23:52 matrix matrix-mautrix-facebook[14118]: [2020-06-09 03:23:52,050] [DEBUG@mau.puppet.100001489252999] Starting syncer for @gergely:horvath.club with sync filter 5.
Jun 09 03:23:53 matrix matrix-mautrix-facebook[14118]: [2020-06-09 03:23:53,407] [ERROR@mau.user.@gergely:horvath.club] Failed to restore session
Jun 09 03:23:53 matrix matrix-mautrix-facebook[14118]: Traceback (most recent call last):
Jun 09 03:23:53 matrix matrix-mautrix-facebook[14118]:   File "/usr/lib/python3.8/site-packages/mautrix_facebook/user.py", line 191, in load_session
Jun 09 03:23:53 matrix matrix-mautrix-facebook[14118]:     session = await fbchat.Session.from_cookies(self._session_data)
Jun 09 03:23:53 matrix matrix-mautrix-facebook[14118]:   File "/usr/lib/python3.8/site-packages/fbchat/_session.py", line 445, in from_cookies
Jun 09 03:23:53 matrix matrix-mautrix-facebook[14118]:     return await cls._from_session(session=session)
Jun 09 03:23:53 matrix matrix-mautrix-facebook[14118]:   File "/usr/lib/python3.8/site-packages/fbchat/_session.py", line 392, in _from_session
Jun 09 03:23:53 matrix matrix-mautrix-facebook[14118]:     define = parse_server_js_define(await r.text())
Jun 09 03:23:53 matrix matrix-mautrix-facebook[14118]:   File "/usr/lib/python3.8/site-packages/fbchat/_session.py", line 35, in parse_server_js_define
Jun 09 03:23:53 matrix matrix-mautrix-facebook[14118]:     raise _exception.ParseError("Could not find any ServerJSDefine", data=html)
Jun 09 03:23:53 matrix matrix-mautrix-facebook[14118]: fbchat.ParseError: Could not find any ServerJSDefine. Please report this, along with the data below!
Jun 09 03:23:53 matrix matrix-mautrix-facebook[14118]: <!DOCTYPE html>
Jun 09 03:23:53 matrix matrix-mautrix-facebook[14118]: <html lang="hu" id="facebook" class="no_js">
Jun 09 03:23:53 matrix matrix-mautrix-facebook[14118]: <head><meta charset="utf-8" /><meta name="referrer" content="default" id="meta_referrer" /><script nonce="JXfiavCv">window._cstart=+new Date();</scri
Jun 09 03:23:53 matrix matrix-mautrix-facebook[14118]: <link type="text/css" rel="stylesheet" href="https://static.xx.fbcdn.net/rsrc.php/v3/yM/l/0,cross/ed1Mxqvuox5.css?_nc_x=Wk8vVCzyNlb" data-bootloader-
Jun 09 03:23:53 matrix matrix-mautrix-facebook[14118]: <link type="text/css" rel="stylesheet" href="https://static.xx.fbcdn.net/rsrc.php/v3/y4/l/0,cross/NFeLw0SE29c.css?_nc_x=Wk8vVCzyNlb" data-bootloader-
Jun 09 03:23:53 matrix matrix-mautrix-facebook[14118]: <link type="text/css" rel="stylesheet" href="https://static.xx.fbcdn.net/rsrc.php/v3/yK/l/0,cross/Bgk9LYYRXAy.css?_nc_x=Wk8vVCzyNlb" data-bootloader-
Jun 09 03:23:53 matrix matrix-mautrix-facebook[14118]: <link type="text/css" rel="stylesheet" href="https://static.xx.fbcdn.net/rsrc.php/v3/yY/l/0,cross/vNkl3MsnzhW.css?_nc_x=Wk8vVCzyNlb" data-bootloader-
```
There is more, but it seems to contain message snippets, I'm not sure if it contains sensitive data, or useful information. If it is needed pls ask for it and tell if something has to be obfuscated like in the previous log.

Has anyone seen it or has any idea what can be the problem? Currently I'm on master (50f379a2fcc46eb2a39eeef8f36c7a06ef52d154).

Thanks!

**Comment by hooger** [comment]
Alright it seems, I figured out. The hint was what the Bridge bot said: find the cookie, messenger.com. So I figured I was trying to log in with Facebook cookie.

So the error was definitely on my part, yet I guess some more emphasize should be given in the login-cookie message, that although the bridge is mautrix-facebook, it only accepts messenger.com links.

As always, thanks for the great work!

**Comment by NicolaiSoeborg** [comment]
I guess the message has been changed since you opened this issue.  I would say the message is fairly clear now, and this issue can be closed:

![image](https://user-images.githubusercontent.com/8722223/95016161-b50af580-0640-11eb-9d5d-38a961874c79.png)
