### ISSUE TITLE
Error appearing in log and when 'sync' called

### ISSUE THREAD

**Issue by matt01** [tulir/mautrix-facebook#64]
Hi, 

I am getting an error in the log and also when I run 'sync' not sure why this is happening, it is only happening to two contacts but I am not sure if that's because I have only messaged two contacts since the problem started.

```
[2020-06-09 17:41:10,238] [ERROR@mau.user.@matt:hostname] Failed to sync thread XXX-FBID-XXXX
Traceback (most recent call last):
  File "/home/matt/matrix/mautrix-facebook/lib/python3.8/site-packages/mautrix_facebook/user.py", line 353, in sync_threads
    await self._sync_thread(thread, ups, contacts)
  File "/home/matt/matrix/mautrix-facebook/lib/python3.8/site-packages/mautrix_facebook/user.py", line 379, in _sync_thread
    await portal.backfill(self, is_initial=False, last_active=thread.last_active)
  File "/home/matt/matrix/mautrix-facebook/lib/python3.8/site-packages/mautrix_facebook/portal.py", line 967, in backfill
    await self._backfill(source, limit, most_recent.date if most_recent else None)
  File "/home/matt/matrix/mautrix-facebook/lib/python3.8/site-packages/mautrix_facebook/portal.py", line 991, in _backfill
    async with NotificationDisabler(self.mxid, source):
  File "/home/matt/matrix/mautrix-facebook/lib/python3.8/site-packages/mautrix/bridge/notification_disabler.py", line 50, in __aenter__
    if not self.intent or not self.config_enabled:
AttributeError: 'NotificationDisabler' object has no attribute 'intent'
```

The version I am running is: mautrix-facebook 0.1.0rc2+dev.unknown.

Thanks, 

Matt.

**Comment by tulir** [comment]
Update to mautrix-python v0.5.4
