### ISSUE TITLE
Failed to update DM portal - You are not invited to this room.

### ISSUE THREAD

**Issue by JuniorJPDJ** [tulir/mautrix-facebook#70]
I probably found why it tried to join this chats in #68...
My log is spammed with errors like this:
```
mautrix-facebook_1  | 2020-06-11T16:46:53.885326647Z [2020-06-11 16:46:53,884] [DEBUG@mau.user.@juniorjpdj:juniorjpdj.pl] Syncing thread <ID> <FB NAME>
mautrix-facebook_1  | 2020-06-11T16:46:54.655555717Z [2020-06-11 16:46:54,654] [ERROR@mau.portal.<ID><-><ID>] Failed to update portal
mautrix-facebook_1  | 2020-06-11T16:46:54.655595407Z Traceback (most recent call last):
mautrix-facebook_1  | 2020-06-11T16:46:54.655605479Z   File "/usr/lib/python3.8/site-packages/mautrix/appservice/api/intent.py", line 357, in ensure_joined
mautrix-facebook_1  | 2020-06-11T16:46:54.655613221Z     await self.join_room(room_id, max_retries=0)
mautrix-facebook_1  | 2020-06-11T16:46:54.655620709Z   File "/usr/lib/python3.8/site-packages/mautrix/appservice/api/intent.py", line 75, in wrapper
mautrix-facebook_1  | 2020-06-11T16:46:54.655646476Z     return await __method(*args, **kwargs)
mautrix-facebook_1  | 2020-06-11T16:46:54.655654782Z   File "/usr/lib/python3.8/site-packages/mautrix/client/api/rooms.py", line 252, in join_room
mautrix-facebook_1  | 2020-06-11T16:46:54.655661978Z     content = await self.api.request(Method.POST, Path.join[room_id_or_alias],
mautrix-facebook_1  | 2020-06-11T16:46:54.655676936Z   File "/usr/lib/python3.8/site-packages/mautrix/api/http.py", line 203, in request
mautrix-facebook_1  | 2020-06-11T16:46:54.655684160Z     return await self._send(method, endpoint, content, query_params, headers or {})
mautrix-facebook_1  | 2020-06-11T16:46:54.655691034Z   File "/usr/lib/python3.8/site-packages/mautrix/api/http.py", line 143, in _send
mautrix-facebook_1  | 2020-06-11T16:46:54.655698022Z     raise make_request_error(http_status=response.status,
mautrix-facebook_1  | 2020-06-11T16:46:54.655704700Z mautrix.errors.request.MForbidden: You are not invited to this room.
mautrix-facebook_1  | 2020-06-11T16:46:54.655711450Z 
mautrix-facebook_1  | 2020-06-11T16:46:54.655717934Z During handling of the above exception, another exception occurred:
mautrix-facebook_1  | 2020-06-11T16:46:54.655724548Z 
mautrix-facebook_1  | 2020-06-11T16:46:54.655730934Z Traceback (most recent call last):
mautrix-facebook_1  | 2020-06-11T16:46:54.655737573Z   File "/usr/lib/python3.8/site-packages/mautrix/appservice/api/intent.py", line 357, in ensure_joined
mautrix-facebook_1  | 2020-06-11T16:46:54.655744601Z     await self.join_room(room_id, max_retries=0)
mautrix-facebook_1  | 2020-06-11T16:46:54.655751208Z   File "/usr/lib/python3.8/site-packages/mautrix/appservice/api/intent.py", line 75, in wrapper
mautrix-facebook_1  | 2020-06-11T16:46:54.655758087Z     return await __method(*args, **kwargs)
mautrix-facebook_1  | 2020-06-11T16:46:54.655764637Z   File "/usr/lib/python3.8/site-packages/mautrix/client/api/rooms.py", line 252, in join_room
mautrix-facebook_1  | 2020-06-11T16:46:54.655771529Z     content = await self.api.request(Method.POST, Path.join[room_id_or_alias],
mautrix-facebook_1  | 2020-06-11T16:46:54.655778329Z   File "/usr/lib/python3.8/site-packages/mautrix/api/http.py", line 203, in request
mautrix-facebook_1  | 2020-06-11T16:46:54.655785255Z     return await self._send(method, endpoint, content, query_params, headers or {})
mautrix-facebook_1  | 2020-06-11T16:46:54.655791981Z   File "/usr/lib/python3.8/site-packages/mautrix/api/http.py", line 143, in _send
mautrix-facebook_1  | 2020-06-11T16:46:54.655798857Z     raise make_request_error(http_status=response.status,
mautrix-facebook_1  | 2020-06-11T16:46:54.655805453Z mautrix.errors.request.MForbidden: You are not invited to this room.
mautrix-facebook_1  | 2020-06-11T16:46:54.655812073Z 
mautrix-facebook_1  | 2020-06-11T16:46:54.655818473Z The above exception was the direct cause of the following exception:
mautrix-facebook_1  | 2020-06-11T16:46:54.655825134Z 
mautrix-facebook_1  | 2020-06-11T16:46:54.655832594Z Traceback (most recent call last):
mautrix-facebook_1  | 2020-06-11T16:46:54.655839216Z   File "/usr/lib/python3.8/site-packages/mautrix_facebook/portal.py", line 323, in update_matrix_room
mautrix-facebook_1  | 2020-06-11T16:46:54.655846152Z     await self._update_matrix_room(source, info)
mautrix-facebook_1  | 2020-06-11T16:46:54.655852874Z   File "/usr/lib/python3.8/site-packages/mautrix_facebook/portal.py", line 332, in _update_matrix_room
mautrix-facebook_1  | 2020-06-11T16:46:54.655867438Z     await puppet.intent.ensure_joined(self.mxid)
mautrix-facebook_1  | 2020-06-11T16:46:54.655874532Z   File "/usr/lib/python3.8/site-packages/mautrix/appservice/api/intent.py", line 363, in ensure_joined
mautrix-facebook_1  | 2020-06-11T16:46:54.655881568Z     await self.bot.invite_user(room_id, self.mxid)
mautrix-facebook_1  | 2020-06-11T16:46:54.655888192Z   File "/usr/lib/python3.8/site-packages/mautrix/appservice/api/intent.py", line 86, in wrapper
mautrix-facebook_1  | 2020-06-11T16:46:54.655895104Z     await __self.ensure_joined(room_id)
mautrix-facebook_1  | 2020-06-11T16:46:54.655901724Z   File "/usr/lib/python3.8/site-packages/mautrix/appservice/api/intent.py", line 361, in ensure_joined
mautrix-facebook_1  | 2020-06-11T16:46:54.655908699Z     raise IntentError(f"Failed to join room {room_id} as {self.mxid}") from e
mautrix-facebook_1  | 2020-06-11T16:46:54.655915744Z mautrix.errors.base.IntentError: Failed to join room !zRYGhtVjBfnyOQDjYZ:juniorjpdj.pl as @facebookbot:juniorjpdj.pl
mautrix-facebook_1  | 2020-06-11T16:46:54.659891771Z [2020-06-11 16:46:54,659] [DEBUG@mau.portal.<ID><-><ID>] Not backfilling <ID><-><ID>: no most recent message found
```

**Comment by mrjohnson22** [comment]
I'm getting bitten by this as well. It has the effect of hiding all messages sent by me from Messenger.

**Comment by mrjohnson22** [comment]
This is caused by having `bridge.invite_own_puppet_to_pm: false` in scenarios that need to invite the puppet, such as backfilling on room creation or sending a message from another client without having enabled double-puppeting.

Setting it to true resolves the errors and allows backfilling & FB->MX messages to work.

**Comment by JuniorJPDJ** [comment]
@mrjohnson22 mine is set to true

**Comment by obbardc** [comment]
so when `bridge.invite_own_puppet_to_pm: true`, all of the messages appear in the chat as expected, but there are three users in the chat. Shouldn't it only be me and the other person ?
It's confusing to see two of me ;-)

![image](https://user-images.githubusercontent.com/1029590/102226527-656a6500-3ee0-11eb-8caa-06202a23c60d.png)

**Comment by obbardc** [comment]
and further to this, i can't seem to change the name of the rooms which were created

**Comment by sentriz** [comment]
I'm still experience this since 7b22460 and using the `refresh` command

```
[2021-01-23 15:58:00,602] [DEBUG@mau.user.@example:example.com] Syncing thread 000000000000000000
[2021-01-23 15:58:00,648] [ERROR@mau.portal.000000000000000<->000000000000000] Failed to update portal
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/mautrix/appservice/api/intent.py", line 329, in ensure_joined
    await self.join_room(room_id, max_retries=0)
  File "/usr/lib/python3.8/site-packages/mautrix/appservice/api/intent.py", line 83, in wrapper
    return await __method(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/mautrix/client/api/rooms.py", line 252, in join_room
    content = await self.api.request(Method.POST, Path.join[room_id_or_alias],
  File "/usr/lib/python3.8/site-packages/mautrix/api.py", line 233, in request
    return await self._send(method, full_url, content, query_params, headers or {})
  File "/usr/lib/python3.8/site-packages/mautrix/api.py", line 158, in _send
    raise make_request_error(http_status=response.status,
mautrix.errors.request.MForbidden: You are not invited to this room.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/mautrix/appservice/api/intent.py", line 329, in ensure_joined
    await self.join_room(room_id, max_retries=0)
  File "/usr/lib/python3.8/site-packages/mautrix/appservice/api/intent.py", line 83, in wrapper
    return await __method(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/mautrix/client/api/rooms.py", line 252, in join_room
    content = await self.api.request(Method.POST, Path.join[room_id_or_alias],
  File "/usr/lib/python3.8/site-packages/mautrix/api.py", line 233, in request
    return await self._send(method, full_url, content, query_params, headers or {})
  File "/usr/lib/python3.8/site-packages/mautrix/api.py", line 158, in _send
    raise make_request_error(http_status=response.status,
mautrix.errors.request.MForbidden: You are not invited to this room.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/mautrix_facebook/portal.py", line 303, in update_matrix_room
    await self._update_matrix_room(source, info)
  File "/usr/lib/python3.8/site-packages/mautrix_facebook/portal.py", line 314, in _update_matrix_room
    await self.update_info(source, info)
  File "/usr/lib/python3.8/site-packages/mautrix_facebook/portal.py", line 195, in update_info
    changed = await self._update_participants(source, info) or changed
  File "/usr/lib/python3.8/site-packages/mautrix_facebook/portal.py", line 294, in _update_participants
    await puppet.intent_for(self).ensure_joined(self.mxid)
  File "/usr/lib/python3.8/site-packages/mautrix/appservice/api/intent.py", line 335, in ensure_joined
    await bot.invite_user(room_id, self.mxid)
  File "/usr/lib/python3.8/site-packages/mautrix/appservice/api/intent.py", line 94, in wrapper
    await __self.ensure_joined(room_id)
  File "/usr/lib/python3.8/site-packages/mautrix/appservice/api/intent.py", line 333, in ensure_joined
    raise IntentError(f"Failed to join room {room_id} as {self.mxid}") from e
mautrix.errors.base.IntentError: Failed to join room !000000000000000:example.com as @facebot:example.com
```

should I need to change the value of `bridge.invite_own_puppet_to_pm`?

thanks!

**Comment by Samgarr** [comment]
Still experiencing this in v0.3.0.
```
[2021-08-03 15:18:11,647] [ERROR@mau.portal.1667462012<->1034320118] Error handling Facebook message mid.$cAAAAAF7FC4qBPd1A4l7DJf4YUwKJ
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/mautrix/appservice/api/intent.py", line 335, in ensure_joined
	await self.join_room(room_id, max_retries=0)
  File "/usr/lib/python3.8/site-packages/mautrix/appservice/api/intent.py", line 83, in wrapper
	return await __method(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/mautrix/client/api/rooms.py", line 252, in join_room
	content = await self.api.request(Method.POST, Path.join[room_id_or_alias],
  File "/usr/lib/python3.8/site-packages/mautrix/api.py", line 254, in request
	return await self._send(method, full_url, content, query_params, headers or {})
  File "/usr/lib/python3.8/site-packages/mautrix/api.py", line 177, in _send
	raise make_request_error(http_status=response.status,
mautrix.errors.request.MForbidden: You are not invited to this room.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/mautrix/appservice/api/intent.py", line 335, in ensure_joined
	await self.join_room(room_id, max_retries=0)
  File "/usr/lib/python3.8/site-packages/mautrix/appservice/api/intent.py", line 83, in wrapper
	return await __method(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/mautrix/client/api/rooms.py", line 252, in join_room
	content = await self.api.request(Method.POST, Path.join[room_id_or_alias],
  File "/usr/lib/python3.8/site-packages/mautrix/api.py", line 254, in request
	return await self._send(method, full_url, content, query_params, headers or {})
  File "/usr/lib/python3.8/site-packages/mautrix/api.py", line 177, in _send
	raise make_request_error(http_status=response.status,
mautrix.errors.request.MForbidden: You are not invited to this room.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/mautrix_facebook/portal.py", line 771, in handle_facebook_message
	await self._handle_facebook_message(source, sender, message, reply_to)
  File "/usr/lib/python3.8/site-packages/mautrix_facebook/portal.py", line 840, in _handle_facebook_message
	event_ids = await self._handle_mqtt_message(source, intent, message, reply_to)
  File "/usr/lib/python3.8/site-packages/mautrix_facebook/portal.py", line 868, in _handle_mqtt_message
	event_ids.append(await self._handle_facebook_text(intent, message, reply_to,
  File "/usr/lib/python3.8/site-packages/mautrix_facebook/portal.py", line 1019, in _handle_facebook_text
	return await self._send_message(intent, content, timestamp=timestamp)
  File "/usr/lib/python3.8/site-packages/mautrix/bridge/portal.py", line 82, in _send_message
	return await intent.send_message_event(self.mxid, event_type, content, **kwargs)
  File "/usr/lib/python3.8/site-packages/mautrix/appservice/api/intent.py", line 94, in wrapper
	await __self.ensure_joined(room_id)
  File "/usr/lib/python3.8/site-packages/mautrix/appservice/api/intent.py", line 341, in ensure_joined
	await bot.invite_user(room_id, self.mxid)
  File "/usr/lib/python3.8/site-packages/mautrix/appservice/api/intent.py", line 94, in wrapper
	await __self.ensure_joined(room_id)
  File "/usr/lib/python3.8/site-packages/mautrix/appservice/api/intent.py", line 339, in ensure_joined
	raise IntentError(f"Failed to join room {room_id} as {self.mxid}") from e
mautrix.errors.base.IntentError: Failed to join room !CNWdaTniCdgvihigiY:XXXX.ZZ as @facebookbot:XXXX.ZZ
```
`invite_own_puppet_to_pm` is set to `true`
