### ISSUE TITLE
Error on chat portal leave

### ISSUE THREAD

**Issue by JuniorJPDJ** [tulir/mautrix-facebook#71]
DM chat portal:
```
mautrix-facebook_1  | 2020-06-12T07:51:46.859528218Z [2020-06-12 07:51:46,857] [ERROR@mau.e2ee] matrix-nio failed to handle membership event
mautrix-facebook_1  | 2020-06-12T07:51:46.859577770Z Traceback (most recent call last):
mautrix-facebook_1  | 2020-06-12T07:51:46.859591980Z   File "/usr/lib/python3.8/site-packages/mautrix/bridge/e2ee.py", line 81, in handle_room_membership
mautrix-facebook_1  | 2020-06-12T07:51:46.859607760Z     if room.handle_membership(nio_evt):
mautrix-facebook_1  | 2020-06-12T07:51:46.859618283Z   File "/usr/lib/python3.8/site-packages/nio/rooms.py", line 320, in handle_membership
mautrix-facebook_1  | 2020-06-12T07:51:46.859629487Z     return self.remove_member(target_user)
mautrix-facebook_1  | 2020-06-12T07:51:46.859639729Z   File "/usr/lib/python3.8/site-packages/nio/rooms.py", line 257, in remove_member
mautrix-facebook_1  | 2020-06-12T07:51:46.859650072Z     self.names[user.name].remove(user.user_id)
mautrix-facebook_1  | 2020-06-12T07:51:46.859663279Z ValueError: list.remove(x): x not in list
mautrix-facebook_1  | 2020-06-12T07:51:46.859728448Z [2020-06-12 07:51:46,859] [INFO@mau.portal.[FBID]<->[FBID] @test:juniorjpdj.pl left private chat portal with [FBID]
```

FB Group chat portal:
```
mautrix-facebook_1  | 2020-06-12T07:53:12.912229519Z [2020-06-12 07:53:12,911] [ERROR@mau.e2ee] matrix-nio failed to handle membership event
mautrix-facebook_1  | 2020-06-12T07:53:12.912283648Z Traceback (most recent call last):
mautrix-facebook_1  | 2020-06-12T07:53:12.912298221Z   File "/usr/lib/python3.8/site-packages/mautrix/bridge/e2ee.py", line 81, in handle_room_membership
mautrix-facebook_1  | 2020-06-12T07:53:12.912310161Z     if room.handle_membership(nio_evt):
mautrix-facebook_1  | 2020-06-12T07:53:12.912350844Z   File "/usr/lib/python3.8/site-packages/nio/rooms.py", line 320, in handle_membership
mautrix-facebook_1  | 2020-06-12T07:53:12.912364334Z     return self.remove_member(target_user)
mautrix-facebook_1  | 2020-06-12T07:53:12.912375204Z   File "/usr/lib/python3.8/site-packages/nio/rooms.py", line 257, in remove_member
mautrix-facebook_1  | 2020-06-12T07:53:12.912385760Z     self.names[user.name].remove(user.user_id)
mautrix-facebook_1  | 2020-06-12T07:53:12.912396020Z ValueError: list.remove(x): x not in list
mautrix-facebook_1  | 2020-06-12T07:53:12.912461106Z [2020-06-12 07:53:12,912] [DEBUG@mau.portal.[FBID]] @test:juniorjpdj.pl left portal to [FBID]
```

**Comment by tulir** [comment]
Fixed when switching away from matrix-nio
