### ISSUE TITLE
ShareAttachment parsing error

### ISSUE THREAD

**Issue by JuniorJPDJ** [tulir/mautrix-facebook#72]
```
mautrix-facebook_1  | 2020-06-12T07:56:16.752333047Z [2020-06-12 07:56:16,751] [ERROR@mau.commands] Unhandled error while handling command sync 10000 --create --contacts from @juniorjpdj:juniorjpdj.pl (ref: 1591923901)                   
mautrix-facebook_1  | 2020-06-12T07:56:16.752388296Z Traceback (most recent call last):                                                                                                                                                      
mautrix-facebook_1  | 2020-06-12T07:56:16.752408322Z   File "/usr/lib/python3.8/site-packages/mautrix/bridge/commands/handler.py", line 359, in handle                                                                                       
mautrix-facebook_1  | 2020-06-12T07:56:16.752423769Z     await self._run_handler(handler, evt)                                                                                                                                               
mautrix-facebook_1  | 2020-06-12T07:56:16.752437285Z   File "/usr/lib/python3.8/site-packages/mautrix/bridge/commands/handler.py", line 253, in __call__                                                                                     
mautrix-facebook_1  | 2020-06-12T07:56:16.752452041Z     return await self._handler(evt)                                                                                                                                                     
mautrix-facebook_1  | 2020-06-12T07:56:16.752463578Z   File "/usr/lib/python3.8/site-packages/mautrix_facebook/commands/facebook.py", line 78, in sync                                                                                       
mautrix-facebook_1  | 2020-06-12T07:56:16.752480451Z     await portal.backfill(evt.sender, is_initial=False, last_active=thread.last_active)
mautrix-facebook_1  | 2020-06-12T07:56:16.752495238Z   File "/usr/lib/python3.8/site-packages/mautrix_facebook/portal.py", line 989, in backfill
mautrix-facebook_1  | 2020-06-12T07:56:16.752507118Z     await self._backfill(source, limit, most_recent.date if most_recent else None)
mautrix-facebook_1  | 2020-06-12T07:56:16.752518611Z   File "/usr/lib/python3.8/site-packages/mautrix_facebook/portal.py", line 996, in _backfill
mautrix-facebook_1  | 2020-06-12T07:56:16.752529841Z     async for message in thread.fetch_messages(limit):
mautrix-facebook_1  | 2020-06-12T07:56:16.752540977Z   File "/usr/lib/python3.8/site-packages/fbchat/_threads/_abc.py", line 405, in fetch_messages
mautrix-facebook_1  | 2020-06-12T07:56:16.752552587Z     messages = await self._fetch_messages(limit, before)
mautrix-facebook_1  | 2020-06-12T07:56:16.752563877Z   File "/usr/lib/python3.8/site-packages/fbchat/_threads/_abc.py", line 375, in _fetch_messages
mautrix-facebook_1  | 2020-06-12T07:56:16.752575537Z     return [
mautrix-facebook_1  | 2020-06-12T07:56:16.752586077Z   File "/usr/lib/python3.8/site-packages/fbchat/_threads/_abc.py", line 376, in <listcomp>
mautrix-facebook_1  | 2020-06-12T07:56:16.752597760Z     _models.MessageData._from_graphql(thread, message, read_receipts)
mautrix-facebook_1  | 2020-06-12T07:56:16.752608650Z   File "/usr/lib/python3.8/site-packages/fbchat/_models/_message.py", line 319, in _from_graphql
mautrix-facebook_1  | 2020-06-12T07:56:16.752619776Z     attachment = graphql_to_extensible_attachment(data["extensible_attachment"])
mautrix-facebook_1  | 2020-06-12T07:56:16.752631379Z   File "/usr/lib/python3.8/site-packages/fbchat/_models/_message.py", line 489, in graphql_to_extensible_attachment
mautrix-facebook_1  | 2020-06-12T07:56:16.752642746Z     return _attachment.ShareAttachment._from_graphql(story)
mautrix-facebook_1  | 2020-06-12T07:56:16.752680516Z   File "/usr/lib/python3.8/site-packages/fbchat/_models/_attachment.py", line 68, in _from_graphql
mautrix-facebook_1  | 2020-06-12T07:56:16.752694209Z     if "/l.php?u=" in url
mautrix-facebook_1  | 2020-06-12T07:56:16.752706238Z TypeError: argument of type 'NoneType' is not iterable
```

**Comment by tulir** [comment]
What kind of message triggered this?

**Comment by JuniorJPDJ** [comment]
I'm not sure now, let me try to reproduce this again yesterday.
Also log is probably not verbose enough for me to be able to find this in messenger log.
Can I somehow attach debugger to this?
I'm running it on server in docker ;/

**Comment by JuniorJPDJ** [comment]
I tried but couldn't reproduce it.
