### ISSUE TITLE
Backfill crash on unavailable photo

### ISSUE THREAD

**Issue by JuniorJPDJ** [tulir/mautrix-facebook#73]
```
mautrix-facebook_1  | [2020-06-12 09:00:47,301] [ERROR@mau.commands] Unhandled error while handling command sync 100 --create --contacts from @test1:juniorjpdj.pl (ref: 1591951115)
mautrix-facebook_1  | Traceback (most recent call last):
mautrix-facebook_1  |   File "/usr/lib/python3.8/site-packages/mautrix/bridge/commands/handler.py", line 359, in handle
mautrix-facebook_1  |     await self._run_handler(handler, evt)
mautrix-facebook_1  |   File "/usr/lib/python3.8/site-packages/mautrix/bridge/commands/handler.py", line 253, in __call__
mautrix-facebook_1  |     return await self._handler(evt)
mautrix-facebook_1  |   File "/usr/lib/python3.8/site-packages/mautrix_facebook/commands/facebook.py", line 78, in sync
mautrix-facebook_1  |     await portal.backfill(evt.sender, is_initial=False, last_active=thread.last_active)
mautrix-facebook_1  |   File "/usr/lib/python3.8/site-packages/mautrix_facebook/portal.py", line 989, in backfill
mautrix-facebook_1  |     await self._backfill(source, limit, most_recent.date if most_recent else None)
mautrix-facebook_1  |   File "/usr/lib/python3.8/site-packages/mautrix_facebook/portal.py", line 1016, in _backfill
mautrix-facebook_1  |     await self.handle_facebook_message(source, puppet, message)
mautrix-facebook_1  |   File "/usr/lib/python3.8/site-packages/mautrix_facebook/portal.py", line 687, in handle_facebook_message
mautrix-facebook_1  |     attach_ids = await asyncio.gather(
mautrix-facebook_1  |   File "/usr/lib/python3.8/site-packages/mautrix_facebook/portal.py", line 782, in _handle_facebook_attachment
mautrix-facebook_1  |     await source.fetch_image_url(attachment.id), intent, encrypt=self.encrypted)
mautrix-facebook_1  |   File "/usr/lib/python3.8/site-packages/fbchat/_client.py", line 478, in fetch_image_url
mautrix-facebook_1  |     _exception.handle_payload_error(j)
mautrix-facebook_1  |   File "/usr/lib/python3.8/site-packages/fbchat/_exception.py", line 123, in handle_payload_error
mautrix-facebook_1  |     raise error_cls(j["errorSummary"], description=j["errorDescription"], code=code)
mautrix-facebook_1  | fbchat.InvalidParameters: #1357031 Te materiały nie są już dostępne: Żądane materiały nie mogą być w tej chwili wyświetlone. Być może są niedostępne tymczasowo lub kliknięty link jest nieaktualny, bądź nie masz uprawnień do przeglądania tej strony
```
The faceboook errorDescription means: 
> Data is no longer available: The requested data cannot be distributed at this time. Perhaps they are temporarily available or the link you clicked is out of date or you do not have permission to create this page

**Comment by tulir** [comment]
Should be fixed as of 2080f4dad9f600aeee0e85f037495265194fec76
