### ISSUE TITLE
cannot login with https://t2bot.io/messenger/

### ISSUE THREAD

**Issue by muniv11111** [tulir/mautrix-facebook#89]
cannot login with https://t2bot.io/messenger/ : with simple Authentication facebook blocked me : login from unknown location, with 2FA got this: Unhandled error while handling command:

Traceback (most recent call last):
File "/home/facebook/fbenv/lib/python3.6/site-packages/mautrix/bridge/commands/handler.py", line 371, in handle
await self._run_handler(handler, evt)
File "/home/facebook/fbenv/lib/python3.6/site-packages/mautrix/bridge/commands/handler.py", line 269, in call
return await self._handler(evt)
File "/home/facebook/fbenv/lib/python3.6/site-packages/mautrix_facebook/commands/auth.py", line 61, in login
user_agent=evt.sender.user_agent)
File "/home/facebook/fbenv/lib/python3.6/site-packages/fbchat/_client.py", line 211, in login
loop=self.loop, log=self._state_log
File "/home/facebook/fbenv/lib/python3.6/site-packages/fbchat/_state.py", line 152, in login
return await cls.from_session(session=session)
File "/home/facebook/fbenv/lib/python3.6/site-packages/fbchat/_state.py", line 191, in from_session
fb_dtsg = FB_DTSG_REGEX.search(text).group(1)
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by tulir** [comment]
GitHub issues are not for t2bot.io support. Also, I think t2bot is running an old version, which is obviously not supported either
