### ISSUE TITLE
Fatal error in listener

### ISSUE THREAD

**Issue by hooger** [tulir/mautrix-facebook#93]
I've also encountered the Fatal error in listener msg. For me it came hand-in-hand with this log:
```
[2020-08-29 08:21:30,221] [DEBUG@mau.user.@gergely:horvath.club] Starting fbchat listener
[2020-08-29 08:21:30,222] [DEBUG@fbchat] Fetching MQTT sequence ID
[2020-08-29 08:21:30,228] [INFO@mau.user.@gergely:horvath.club] Running post-login actions
[2020-08-29 08:21:30,229] [DEBUG@mau.user.@gergely:horvath.club] Fetching contacts...
[2020-08-29 08:21:30,325] [ERROR@mau.user.@gergely:horvath.club] Fatal error in listener
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/mautrix_facebook/user.py", line 482, in _try_listen
    await self._listen()
  File "/usr/lib/python3.8/site-packages/mautrix_facebook/user.py", line 511, in _listen
    async for event in self.listener.listen():
  File "/usr/lib/python3.8/site-packages/fbchat/_listen.py", line 353, in listen
    self._sequence_id = await fetch_sequence_id(self.session)
  File "/usr/lib/python3.8/site-packages/fbchat/_listen.py", line 115, in fetch_sequence_id
    (j,) = await session._graphql_requests(_graphql.from_doc_id("1349387578499440", params))
  File "/usr/lib/python3.8/site-packages/fbchat/_session.py", line 555, in _graphql_requests
    return await self._post("/api/graphqlbatch/", data, as_graphql=True)
  File "/usr/lib/python3.8/site-packages/fbchat/_session.py", line 519, in _post
    _exception.handle_http_error(r.status)
  File "/usr/lib/python3.8/site-packages/fbchat/_exception.py", line 152, in handle_http_error
    raise HTTPError(
fbchat.HTTPError: Got 500 response: There is probably an error on the endpoint, or it might be rate limited
[2020-08-29 08:21:30,326] [DEBUG@mau.user.@gergely:horvath.club] Sending bridge notice: Fatal error in listener (see logs for more info)
```

During the error msg-s were bridged but didn't arrived. They also didn't arrived from the puppet user. After sending a new refresh (which still produced the issue) my msgs were backfilled but earlier form contact did not.
Refresh didn't help, but after restarting, the error went away.

## Msg history:
- Contact: msg1
- Me: msg2
- C: msg3
- M: msg4
refresh1 and get msg of Fatal error
- M: msg5 with FB
refresh2 and get msg of Fatal error
Restart bridge
- M: msg6

At msg4 I figured there may be some trouble, so `refresh` and realized, that there is. The lost msg is "msg3". It wasn't backfilled, even when "msg5" was (which wasn't bridged when sent).

## Reasoning
The issues is opened
1) to tell others that it has been experienced by others,
2) because there was also some hicup with the backfilling,
3) mostly to log what I've seen.

**Comment by wvffle** [comment]
Same here. Happens randomly when doing `sync` and pretty much every time I run `refresh` or start the container.

**Comment by matt01** [comment]
I'm getting the same issue, I get messages that dont arrive from facebook and 500 errors when attempting to send a message, Interesting it will happen on sending a message but if I send it again the message goes through.

Not sure what has caused it, however, it all suddenly started happening at the same time, I'm guessing facebook have changed something.
